// SPDX-License-Identifier: GPL-2.0-only
// RTL8188EUProbe.cpp — see header. Register constants are from Linux
// drivers/net/wireless/realtek/rtl8xxxu/{rtl8xxxu.h,regs.h} (verified 2026-10-07).

#include "RTL8188EUProbe.hpp"
#include <IOKit/IOLib.h>
#include <IOKit/usb/StandardUSB.h>
#include "rtl8188eu_fw.h"   // generated by scripts/fetch-rtl8188eu-fw.sh (rtl8188eu_fw[], rtl8188eu_fw_len)
#include "rtl8188eu_tables.h" // generated by scripts/gen-rtl8188eu-tables.py (rtl8188e_mac_init_table[])

#define super IOService
OSDefineMetaClassAndStructors(RTL8188EUProbe, IOService)

#define LOGP "RTL8188EUProbe: "

enum {
    kRealtekUsbRead   = 0xC0,   // REALTEK_USB_READ
    kRealtekUsbWrite  = 0x40,   // REALTEK_USB_WRITE
    kRealtekUsbCmdReq = 0x05,   // REALTEK_USB_CMD_REQ
    kRegSysCfg        = 0x00F0, // REG_SYS_CFG
    kSysCfgChipVerMask  = 0xF000, // SYS_CFG_CHIP_VERSION_MASK (bits 12-15)
    kSysCfgTrpVauxEn    = 1u << 23, // SYS_CFG_TRP_VAUX_EN (test chip)
    kCtlTimeoutMs     = 500,    // RTW_USB_CONTROL_MSG_TIMEOUT

    // regs.h
    kRegSysIsoCtrl    = 0x0000, kSysIsoPwcEv12v = 1u << 15,
    kRegSysFunc       = 0x0002, kSysFuncEldr    = 1u << 12,
    kRegSysClkr       = 0x0008, kSysClkAna8m    = 1u << 1, kSysClkLoaderEnable = 1u << 5,
    kReg9346Cr        = 0x000A, kEepromBoot     = 1u << 4, kEepromEnable = 1u << 5,
    kRegEfuseCtrl     = 0x0030,
    kRegEfuseAccess   = 0x00CF, kEfuseAccessEnable = 0x69, kEfuseAccessDisable = 0x00,
    // rtl8xxxu.h
    kEfuseMapLen      = 512,    // EFUSE_MAP_LEN == EFUSE_REAL_CONTENT_LEN_8723A
    kEfuseMaxWordUnit = 4,
    kMaxRegPoll       = 500,    // RTL8XXXU_MAX_REG_POLL
    // Stage 3b power_on (8188e.c rtl8188e_disabled_to_emu / emu_to_active / rtl8188eu_power_on)
    kRegApsFsmco      = 0x0004,
    kFsmcoMacEnable   = 1u << 8, kFsmcoHwSuspend = 1u << 11, kFsmcoPcie = 1u << 12,
    kFsmcoHwPowerdown = 1u << 15, kFsmcoPowerReady = 1u << 17,   // BIT(17) written as literal in 8188e.c
    kSysFuncBbrstb    = 1u << 0, kSysFuncBbGlbRstn = 1u << 1,
    kRegAfeXtalCtrl   = 0x0024, kAfeXtalSchmitt = 1u << 23,
    kRegLpldoCtrl     = 0x0023, kLpldoSleep = 1u << 4,
    kRegCr            = 0x0100,
    kRegMaxAggrNum    = 0x04ca,  // REG_MAX_AGGR_NUM (regs.h:634)
    // Stage 3c-2 BB init / RF access (regs.h, verified 2026-10-07)
    kSysFuncUsba = 1u << 2, kSysFuncUsbd = 1u << 4, kSysFuncDioRf = 1u << 13,
    kRegRfCtrl = 0x001f, kRfEnable = 1u << 0, kRfRstb = 1u << 1, kRfSdmrstb = 1u << 2,
    kRegFpgaXaHssiParm1 = 0x0820, kFpgaHssiParm1Pi = 1u << 8,
    kRegFpgaXaHssiParm2 = 0x0824, kHssiParm2AddrShift = 23, kHssiParm2AddrMask = 0x7f800000u,
    kHssiParm2EdgeRead = 1u << 31,
    kRegFpgaXaRfIntOe = 0x0860, kRegFpgaXaRfSwCtrl = 0x0870, kFpgaRfRfEnv = 1u << 4,
    kHssi3WireDataLen = 0x800, kHssi3WireAddrLen = 0x400,
    kRegFpgaXaLssiParm = 0x0840, kLssiParmAddrShift = 20, kLssiParmDataMask = 0x000fffff,
    kRegFpgaXaLssiReadback = 0x08a0, kRegHspiXaReadback = 0x08b8,
    kCrHciTxdma = 1u << 0, kCrHciRxdma = 1u << 1, kCrTxdma = 1u << 2, kCrRxdma = 1u << 3,
    kCrProtocol = 1u << 4, kCrSchedule = 1u << 5, kCrSecurity = 1u << 9, kCrCaltimer = 1u << 10,
    kSysClkMacClkEnable = 1u << 11,
    // Stage 3b-2 firmware (regs.h / rtl8xxxu.h / 8188e.c, verified 2026-10-07)
    kRegMcuFwDl       = 0x0080,
    kFwDlEnable = 1u << 0, kFwDlReady = 1u << 1, kFwDlCsumReport = 1u << 2,
    kFwDlWintInitReady = 1u << 6, kFwDlRamSel = 1u << 7,
    kSysFuncCpuEnable = 1u << 10,
    kRegFwStart       = 0x1000,   // REG_FW_START_ADDRESS
    kFwPageSize       = 4096,     // RTL_FW_PAGE_SIZE
    kFwPollMax        = 1000,     // RTL8XXXU_FIRMWARE_POLL_MAX
    kFwHeaderLen      = 32,       // sizeof(struct rtl8xxxu_firmware_header)
    kWriteNBlock      = 196,      // rtl8188eu_fops.writeN_block_size
    kRegTrxdmaCtrl    = 0x010C,
    kQueueLow = 1, kQueueNormal = 2, kQueueHigh = 3,           // TRXDMA_QUEUE_*
    kRegTrxffBndy     = 0x0114, kTrxffBoundary8188e = 0x25ff,
    kRegRqpn          = 0x0200, kRegRqpnNpq = 0x0214, kRqpnLoad = 1u << 31,
    kTxTotalPage8188e = 0xa9, kTxPageHi8188e = 0x29, kTxPageLo8188e = 0x1c, kTxPageNorm8188e = 0x1c,
    // Stage 3c-4 WMAC/LLT block (regs.h, verified 2026-10-07 against build/src/regs.h)
    kRegLltInit = 0x01e0, kLltOpWrite = 1u << 30, kLltOpMask = 3u << 30, kLltPoll = 20,
    kLastLltEntry8188e = 175,
    kRegTxpktbufBcnqBdny = 0x0424, kRegTxpktbufMgqBdny = 0x0425, kRegTxpktbufWmacLbkBfHd = 0x045d,
    kRegTdectrl = 0x0208, kRegPbp = 0x0104, kPbpPageSize128 = 1, kPbpRxShift = 0, kPbpTxShift = 4,
    kFpga0RfTrsw = 1u << 5, kFpga0RfTrswb = 1u << 6, kFpga0RfAntsw = 1u << 8, kFpga0RfAntswb = 1u << 9,
    kFpga0RfPape = 1u << 10, kFpga0RfBdCtrlShift = 16,
    kCrMacTxEnable = 1u << 6, kCrMacRxEnable = 1u << 7,
    kRegTxdmaOffsetChk = 0x020c, kTxdmaOffsetDropDataEn = 1u << 9,
    kRegEarlyModeControl8188e = 0x04d0,
    kRegTxReportCtrl = 0x04ec, kTxReportCtrlTimerEnable = 1u << 1, kRegTxReportTime = 0x04f0,
    kRegRxDrvinfoSz = 0x060f,
    kRegHisr0 = 0x00b4, kRegHimr0 = 0x00b0, kRegHimr1 = 0x00b8,
    kImr0Pstimeout = 1u << 29, kImr0Tbder = 1u << 26, kImr0Cpwm = 1u << 8, kImr0Cpwm2 = 1u << 9,
    kImr1Txerr = 1u << 11, kImr1Rxerr = 1u << 10, kImr1Txfovw = 1u << 9, kImr1Rxfovw = 1u << 8,
    kRegUsbSpecialOption = 0xfe55, kUsbSpecIntBulkSelect = 1u << 4, kUsbSpecUsbAggEnable = 1u << 3,
    kTrxdmaCtrlRxdmaAggEn = 1u << 2,
    kRegRcr = 0x0608, kRcrAcceptPhysMatch = 1u << 1, kRcrAcceptMcast = 1u << 2, kRcrAcceptBcast = 1u << 3,
    kRcrAcceptMgmtFrame = 1u << 13, kRcrHtcLocCtrl = 1u << 14,
    kRcrAppendPhystat = 1u << 28, kRcrAppendIcv = 1u << 29, kRcrAppendMic = 1u << 30,
    kRegMar = 0x0620,
    kRegResponseRateSet = 0x0440, kResponseRateBitmapAll = 0xfffff, kResponseRateRrsrCckOnly1m = 0xffff1,
    kRegSpecSifs = 0x0428, kRegRetryLimit = 0x042a,
    kRegMacSpecSifs = 0x063a, kRegSifsCck = 0x0514, kRegSifsOfdm = 0x0516,
    kRegEdcaBe = 0x0508, kRegEdcaBk = 0x050c, kRegEdcaVi = 0x0504, kRegEdcaVo = 0x0500,
    kRegDarfrc = 0x0430, kRegRarfrc = 0x0438,
    kRegFwhwTxqCtrl = 0x0420, kFwhwTxqCtrlAmpduRetry = 1u << 7,
    kRegAckto = 0x0640,
    kRegBeaconCtrl = 0x0550, kBeaconDisableTsfUpdate = 1u << 4,
    kRegTbttProhibit = 0x0540, kRegDriverEarlyInt = 0x0558, kDriverEarlyIntTime = 5,
    kRegBeaconDmaTime = 0x0559, kBeaconDmaAtimeIntTime = 2, kRegBeaconTcfg = 0x0510,
    kRegPktVoViLifeTime = 0x04c0, kRegPktBeBkLifeTime = 0x04c2,
    kRegFpga0RfMode = 0x0800, kFpgaRfModeCck = 1u << 24, kFpgaRfModeOfdm = 1u << 25,
    kRegCamCmd = 0x0670, kCamCmdPolling = 1u << 31,
    // Stage 3c-5 tail of init_device (regs.h / rtl8xxxu.h / 8188f.c, verified 2026-10-07)
    kEfuseOffCckBaseA = 0x10, kEfuseOffHt40BaseA = 0x16,        // struct rtl8188eu_efuse.tx_power_index_A
    kRegTxAgcACck1Mcs32 = 0x0e08, kRegTxAgcBCck11ACck211 = 0x086c,
    kRegTxAgcARate1806 = 0x0e00, kRegTxAgcARate5424 = 0x0e04,
    kRegTxAgcAMcs0300 = 0x0e10, kRegTxAgcAMcs0704 = 0x0e14, kRegTxAgcAMcs1108 = 0x0e18, kRegTxAgcAMcs1512 = 0x0e1c,
    kRegLedcfg2 = 0x004e, kLedcfg2DpdtSelect = 1u << 7,
    kRegHwseqCtrl = 0x0423, kRegBarModeCtrl = 0x04cc,
    kRegGpioMuxcfg = 0x0040, kGpioMuxcfgIoSelEnbt = 1u << 5,
    kRegTxpause = 0x0522, kRegOfdm1Lstf = 0x0d00, kOfdmLstfMask = 0x70000000,
    kRf6052RegAc = 0x00, kRf6052RegModeAg = 0x18, kRf6052RegTMeter8723b = 0x42,
    kRegNavUpper = 0x0652, kNavUpperUnit = 128, kRegUsbHrpwm = 0xfe58,
    kFwhwTxqCtrlXmitMgmtAck = 1u << 12,
    // struct rtl8188eu_efuse (rtl8xxxu.h)
    kEfuseRtlId       = 0x8129, kEfuseOffMac = 0xD7,
};

IOReturn RTL8188EUProbe::regRead(uint16_t addr, void *out, uint16_t len)
{
    if (!_iface || !_ctlBuf || len > 4) return kIOReturnNotReady;
    StandardUSB::DeviceRequest req = {};
    req.bmRequestType = kRealtekUsbRead;
    req.bRequest      = kRealtekUsbCmdReq;
    req.wValue        = addr;   // x86_64 only: host order == USB little-endian
    req.wIndex        = 0;
    req.wLength       = len;
    uint32_t got = 0;
    IOReturn r = _iface->deviceRequest(req, _ctlBuf, got, kCtlTimeoutMs);
    if (r != kIOReturnSuccess) return r;
    if (got != len) return kIOReturnUnderrun;
    bcopy(_ctlBuf->getBytesNoCopy(), out, len);
    return kIOReturnSuccess;
}

IOReturn RTL8188EUProbe::regWrite(uint16_t addr, const void *in, uint16_t len)
{
    if (!_iface || !_ctlBuf || len > 4) return kIOReturnNotReady;
    bcopy(in, _ctlBuf->getBytesNoCopy(), len);
    StandardUSB::DeviceRequest req = {};
    req.bmRequestType = kRealtekUsbWrite;
    req.bRequest      = kRealtekUsbCmdReq;
    req.wValue        = addr;
    req.wIndex        = 0;
    req.wLength       = len;
    uint32_t got = 0;
    IOReturn r = _iface->deviceRequest(req, _ctlBuf, got, kCtlTimeoutMs);
    if (r != kIOReturnSuccess) return r;
    return got == len ? kIOReturnSuccess : kIOReturnUnderrun;
}

// Port of rtl8xxxu_read_efuse8 (core.c): select offset, clear bit 31 of ctrl+3,
// poll ctrl bit 31 for completion, then data is in the low byte.
IOReturn RTL8188EUProbe::efuseRead8(uint16_t offset, uint8_t *data)
{
    uint8_t v8; uint32_t v32 = 0; IOReturn r;

    if ((r = write8(kRegEfuseCtrl + 1, offset & 0xff)) != kIOReturnSuccess) return r;
    if ((r = read8(kRegEfuseCtrl + 2, &v8)) != kIOReturnSuccess) return r;
    v8 = (v8 & 0xfc) | ((offset >> 8) & 0x03);
    if ((r = write8(kRegEfuseCtrl + 2, v8)) != kIOReturnSuccess) return r;

    if ((r = read8(kRegEfuseCtrl + 3, &v8)) != kIOReturnSuccess) return r;
    if ((r = write8(kRegEfuseCtrl + 3, v8 & 0x7f)) != kIOReturnSuccess) return r;

    int i;
    for (i = 0; i < kMaxRegPoll; i++) {
        if ((r = read32(kRegEfuseCtrl, &v32)) != kIOReturnSuccess) return r;
        if (v32 & (1u << 31)) break;
    }
    if (i == kMaxRegPoll) return kIOReturnTimeout;

    IODelay(50);
    if ((r = read32(kRegEfuseCtrl, &v32)) != kIOReturnSuccess) return r;
    *data = v32 & 0xff;
    return kIOReturnSuccess;
}

// Port of rtl8xxxu_read_efuse (core.c). is_multi_func branch omitted: it is not
// set for the 8188EU (assumption: not verified against 8188e.c fops).
// Writes only the efuse access/power/clock enables, exactly as Linux does before power-on.
IOReturn RTL8188EUProbe::efuseReadAll()
{
    IOReturn r;
    uint16_t v16;

    if ((r = read16(kReg9346Cr, &v16)) != kIOReturnSuccess) return r;
    IOLog(LOGP "9346CR=0x%04x boot=%s%s\n", v16, (v16 & kEepromBoot) ? "EEPROM" : "EFUSE",
          (v16 & kEepromEnable) ? " (EEPROM present)" : "");

    memset(_efuse, 0xff, sizeof(_efuse));
    if ((r = write8(kRegEfuseAccess, kEfuseAccessEnable)) != kIOReturnSuccess) return r;

    do {
        if ((r = read16(kRegSysIsoCtrl, &v16)) != kIOReturnSuccess) break;
        if (!(v16 & kSysIsoPwcEv12v) &&
            (r = write16(kRegSysIsoCtrl, v16 | kSysIsoPwcEv12v)) != kIOReturnSuccess) break;

        if ((r = read16(kRegSysFunc, &v16)) != kIOReturnSuccess) break;
        if (!(v16 & kSysFuncEldr) &&
            (r = write16(kRegSysFunc, v16 | kSysFuncEldr)) != kIOReturnSuccess) break;

        if ((r = read16(kRegSysClkr, &v16)) != kIOReturnSuccess) break;
        uint16_t need = kSysClkLoaderEnable | kSysClkAna8m;
        if ((v16 & need) != need &&
            (r = write16(kRegSysClkr, v16 | need)) != kIOReturnSuccess) break;

        uint16_t addr = 0;
        while (addr < kEfuseMapLen) {
            uint8_t header, ext, val8;
            uint16_t offset, mask;
            if ((r = efuseRead8(addr++, &header)) != kIOReturnSuccess) break;
            if (header == 0xff) break;
            if ((header & 0x1f) == 0x0f) {              // extended header
                offset = (header & 0xe0) >> 5;
                if ((r = efuseRead8(addr++, &ext)) != kIOReturnSuccess) break;
                if ((ext & 0x0f) == 0x0f) continue;     // all words disabled
                offset |= (ext & 0xf0) >> 1;
                mask = ext & 0x0f;
            } else {
                offset = (header >> 4) & 0x0f;
                mask = header & 0x0f;
            }
            uint16_t map = offset * 8;
            for (int i = 0; i < kEfuseMaxWordUnit; i++) {
                if (mask & (1u << i)) { map += 2; continue; }
                if ((r = efuseRead8(addr++, &val8)) != kIOReturnSuccess) break;
                if (map >= kEfuseMapLen - 1) { IOLog(LOGP "illegal efuse map_addr 0x%04x\n", map); r = kIOReturnBadArgument; break; }
                _efuse[map++] = val8;
                if ((r = efuseRead8(addr++, &val8)) != kIOReturnSuccess) break;
                _efuse[map++] = val8;
            }
            if (r != kIOReturnSuccess) break;
        }
    } while (0);

    write8(kRegEfuseAccess, kEfuseAccessDisable);   // always restore
    return r;
}

void RTL8188EUProbe::logEfuse()
{
    uint16_t id = (uint16_t)(_efuse[0] | (_efuse[1] << 8));
    const uint8_t *m = &_efuse[kEfuseOffMac];
    IOLog(LOGP "efuse rtl_id=0x%04x (%s, expect 0x%04x)\n", id,
          id == kEfuseRtlId ? "OK" : "MISMATCH", kEfuseRtlId);
    IOLog(LOGP "efuse MAC %02x:%02x:%02x:%02x:%02x:%02x\n", m[0], m[1], m[2], m[3], m[4], m[5]);
    for (int row = 0; row < 16; row++) {
        const uint8_t *b = &_efuse[row * 16];
        IOLog(LOGP "efuse[%03x] %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x\n",
              row * 16, b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7],
              b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15]);
    }
}

// Port of rtl8188eu_power_on (8188e.c). Does NOT touch TX/RX MAC enable (hw bug note in source).
IOReturn RTL8188EUProbe::powerOn()
{
    uint16_t v16; uint32_t v32 = 0; uint8_t v8;
    IOReturn r;
    #define TRY(x) do { r = (x); if (r != kIOReturnSuccess) { IOLog(LOGP "powerOn: %s failed 0x%08x\n", #x, r); return r; } } while (0)

    // rtl8188e_disabled_to_emu
    TRY(read16(kRegApsFsmco, &v16));
    v16 &= ~(kFsmcoHwSuspend | kFsmcoPcie);
    TRY(write16(kRegApsFsmco, v16));

    // rtl8188e_emu_to_active: wait 0x04[17] power ready
    int count;
    for (count = kMaxRegPoll; count; count--) {
        TRY(read32(kRegApsFsmco, &v32));
        if (v32 & kFsmcoPowerReady) break;
        IODelay(10);
    }
    if (!count) { IOLog(LOGP "powerOn: power-ready (0x04[17]) timeout, FSMCO=0x%08x\n", v32); return kIOReturnTimeout; }

    TRY(read8(kRegSysFunc, &v8));                       // reset baseband
    v8 &= ~(kSysFuncBbrstb | kSysFuncBbGlbRstn);
    TRY(write8(kRegSysFunc, v8));

    TRY(read32(kRegAfeXtalCtrl, &v32));                 // schmitt trigger
    v32 |= kAfeXtalSchmitt;
    TRY(write32(kRegAfeXtalCtrl, v32));

    TRY(read16(kRegApsFsmco, &v16));                    // disable HWPDN
    v16 &= ~kFsmcoHwPowerdown;
    TRY(write16(kRegApsFsmco, v16));

    TRY(read16(kRegApsFsmco, &v16));                    // disable WL suspend
    v16 &= ~(kFsmcoHwSuspend | kFsmcoPcie);
    TRY(write16(kRegApsFsmco, v16));

    TRY(read32(kRegApsFsmco, &v32));                    // set MAC_ENABLE, poll until it clears
    v32 |= kFsmcoMacEnable;
    TRY(write32(kRegApsFsmco, v32));
    for (count = kMaxRegPoll; count; count--) {
        TRY(read32(kRegApsFsmco, &v32));
        if (!(v32 & kFsmcoMacEnable)) break;
        IODelay(10);
    }
    if (!count) { IOLog(LOGP "powerOn: MAC_ENABLE did not clear, FSMCO=0x%08x\n", v32); return kIOReturnTimeout; }

    TRY(read8(kRegLpldoCtrl, &v8));                     // LDO normal mode
    v8 &= ~kLpldoSleep;
    TRY(write8(kRegLpldoCtrl, v8));

    v16 = kCrHciTxdma | kCrHciRxdma | kCrTxdma | kCrRxdma |
          kCrProtocol | kCrSchedule | kCrSecurity | kCrCaltimer;
    TRY(write16(kRegCr, v16));
    #undef TRY
    return kIOReturnSuccess;
}

// Port of rtl8xxxu_writeN: control writes of at most 196 bytes, wValue advancing per chunk.
IOReturn RTL8188EUProbe::regWriteN(uint16_t addr, const uint8_t *buf, uint32_t len)
{
    if (!_iface || !_blkBuf) return kIOReturnNotReady;
    while (len) {
        uint32_t n = len > kWriteNBlock ? kWriteNBlock : len;
        bcopy(buf, _blkBuf->getBytesNoCopy(), n);
        StandardUSB::DeviceRequest req = {};
        req.bmRequestType = kRealtekUsbWrite;
        req.bRequest      = kRealtekUsbCmdReq;
        req.wValue        = addr;
        req.wIndex        = 0;
        req.wLength       = (uint16_t)n;
        uint32_t got = 0;
        IOReturn r = _iface->deviceRequest(req, _blkBuf, got, kCtlTimeoutMs);
        if (r != kIOReturnSuccess || got != n) {
            IOLog(LOGP "writeN failed at 0x%04x len %u: 0x%08x got %u\n", addr, n, r, got);
            return r != kIOReturnSuccess ? r : kIOReturnUnderrun;
        }
        addr += n; buf += n; len -= n;
    }
    return kIOReturnSuccess;
}

// Ports of rtl8xxxu_init_queue_reserved_page (core.c:3815), rtl8xxxu_init_queue_priority (core.c:2580,
// cases 2 and 3) and the REG_TRXFF_BNDY+2 write, in the order of core.c:3990-4001.
// 8188eu uses config_endpoints_no_sie (8188e.c:418, core.c:1717): 1st OUT ep = high, 2nd = normal,
// 3rd+ = low. The user's dongle has 2 bulk OUT (0x02, 0x03) => high + normal, no low queue.
// GUESS: Linux skips the reserved-page write if the MAC was already powered before power_on;
// we always write it (fresh plug assumed).
IOReturn RTL8188EUProbe::initQueues()
{
    IOReturn r;
    if (_nBulkOut != 2 && _nBulkOut != 3) {
        IOLog(LOGP "initQueues: unsupported bulk OUT count %u (handled: 2, 3)\n", _nBulkOut);
        return kIOReturnUnsupported;
    }
    const bool hasLow = (_nBulkOut == 3);

    uint32_t hq = kTxPageHi8188e, lq = hasLow ? kTxPageLo8188e : 0, nq = kTxPageNorm8188e;
    uint32_t pubq = kTxTotalPage8188e - hq - lq - nq - 1;
    if ((r = write32(kRegRqpnNpq, (nq << 0) | (0u << 16))) != kIOReturnSuccess) return r;
    if ((r = write32(kRegRqpn, kRqpnLoad | (hq << 0) | (lq << 8) | (pubq << 16))) != kIOReturnSuccess) return r;

    // core.c case 3: VO,MG,HI=high VI=normal BE,BK=low. case 2 (high+normal): VO,VI,MG,HI=high BE,BK=normal.
    const uint16_t voq = kQueueHigh, miq = kQueueHigh;
    const uint16_t viq = hasLow ? kQueueNormal : kQueueHigh;
    const uint16_t beq = hasLow ? kQueueLow : kQueueNormal;
    IOLog(LOGP "initQueues: %u bulk OUT, %s low queue\n", _nBulkOut, hasLow ? "with" : "no");

    uint16_t v16;
    if ((r = read16(kRegTrxdmaCtrl, &v16)) != kIOReturnSuccess) return r;
    v16 &= 0x7;
    v16 |= (voq << 4) | (viq << 6) | (beq << 8) | (beq << 10) | (miq << 12) | (miq << 14);   // VO VI BE BK MG HI
    if ((r = write16(kRegTrxdmaCtrl, v16)) != kIOReturnSuccess) return r;

    return write16(kRegTrxffBndy + 2, kTrxffBoundary8188e);
}

// rtl8188eu_reset_8051 (8188e.c:558)
IOReturn RTL8188EUProbe::reset8051()
{
    uint16_t sf; IOReturn r;
    if ((r = read16(kRegSysFunc, &sf)) != kIOReturnSuccess) return r;
    sf &= ~kSysFuncCpuEnable;
    if ((r = write16(kRegSysFunc, sf)) != kIOReturnSuccess) return r;
    sf |= kSysFuncCpuEnable;
    return write16(kRegSysFunc, sf);
}

// Port of rtl8xxxu_download_firmware (core.c:2004), payload = blob minus 32-byte header.
IOReturn RTL8188EUProbe::fwDownload()
{
    #define TRY(x) do { r = (x); if (r != kIOReturnSuccess) { IOLog(LOGP "fwDownload: %s failed 0x%08x\n", #x, r); goto abort; } } while (0)
    IOReturn r; uint8_t v8; uint16_t v16; uint32_t v32;
    const uint8_t *fw = rtl8188eu_fw + kFwHeaderLen;
    uint32_t size = rtl8188eu_fw_len - kFwHeaderLen, pages = size / kFwPageSize, rem = size % kFwPageSize, i;

    TRY(read8(kRegSysFunc + 1, &v8));  TRY(write8(kRegSysFunc + 1, v8 | 4));
    TRY(read16(kRegSysFunc, &v16));    TRY(write16(kRegSysFunc, v16 | kSysFuncCpuEnable));

    TRY(read8(kRegMcuFwDl, &v8));
    if (v8 & kFwDlRamSel) {
        IOLog(LOGP "firmware already running, resetting MCU\n");
        TRY(write8(kRegMcuFwDl, 0x00));
        TRY(reset8051());
    }
    TRY(read8(kRegMcuFwDl, &v8));      TRY(write8(kRegMcuFwDl, v8 | kFwDlEnable));
    TRY(read32(kRegMcuFwDl, &v32));    TRY(write32(kRegMcuFwDl, v32 & ~(1u << 19)));   // 8051 reset
    TRY(read8(kRegMcuFwDl, &v8));      TRY(write8(kRegMcuFwDl, v8 | kFwDlCsumReport)); // reset checksum

    for (i = 0; i < pages; i++) {
        TRY(read8(kRegMcuFwDl + 2, &v8));
        TRY(write8(kRegMcuFwDl + 2, (uint8_t)((v8 & 0xF8) | i)));
        TRY(regWriteN(kRegFwStart, fw, kFwPageSize));
        fw += kFwPageSize;
    }
    if (rem) {
        TRY(read8(kRegMcuFwDl + 2, &v8));
        TRY(write8(kRegMcuFwDl + 2, (uint8_t)((v8 & 0xF8) | i)));
        TRY(regWriteN(kRegFwStart, fw, rem));
    }
    r = kIOReturnSuccess;
abort:
    // always: MCU firmware download disable (16-bit)
    if (read16(kRegMcuFwDl, &v16) == kIOReturnSuccess) write16(kRegMcuFwDl, v16 & ~kFwDlEnable);
    return r;
    #undef TRY
}

// Port of rtl8xxxu_start_firmware (core.c:1944). 8188eu: no HMTFR write (init_reg_hmtfr unset).
IOReturn RTL8188EUProbe::fwStart()
{
    uint32_t v32 = 0; IOReturn r; int i;
    for (i = 0; i < kFwPollMax; i++) {
        if ((r = read32(kRegMcuFwDl, &v32)) != kIOReturnSuccess) return r;
        if (v32 & kFwDlCsumReport) break;
    }
    if (i == kFwPollMax) { IOLog(LOGP "firmware checksum poll timed out, FW_DL=0x%08x\n", v32); return kIOReturnTimeout; }

    if ((r = read32(kRegMcuFwDl, &v32)) != kIOReturnSuccess) return r;
    v32 |= kFwDlReady; v32 &= ~kFwDlWintInitReady;
    if ((r = write32(kRegMcuFwDl, v32)) != kIOReturnSuccess) return r;
    if ((r = reset8051()) != kIOReturnSuccess) return r;

    for (i = 0; i < kFwPollMax; i++) {
        if ((r = read32(kRegMcuFwDl, &v32)) != kIOReturnSuccess) return r;
        if (v32 & kFwDlWintInitReady) break;
        IODelay(100);
    }
    if (i == kFwPollMax) { IOLog(LOGP "firmware failed to start, FW_DL=0x%08x\n", v32); return kIOReturnTimeout; }
    return kIOReturnSuccess;
}

IOReturn RTL8188EUProbe::loadFirmware()
{
    if (rtl8188eu_fw_len <= kFwHeaderLen) return kIOReturnBadArgument;
    uint16_t sig = rtl8188eu_fw[0] | (rtl8188eu_fw[1] << 8);
    switch (sig & 0xfff0) {   // core.c:2140 accepted signatures
    case 0x92e0: case 0x92c0: case 0x88e0: case 0x88c0: case 0x5300:
    case 0x2300: case 0x88f0: case 0x10b0: case 0x92f0: break;
    default: IOLog(LOGP "invalid firmware signature 0x%04x\n", sig); return kIOReturnBadArgument;
    }
    IOLog(LOGP "firmware %u bytes, revision %u.%u signature 0x%04x\n", rtl8188eu_fw_len,
          rtl8188eu_fw[4] | (rtl8188eu_fw[5] << 8), rtl8188eu_fw[6], sig);

    IOReturn r = initQueues();
    if (r != kIOReturnSuccess) { IOLog(LOGP "initQueues failed 0x%08x\n", r); return r; }

    for (int retry = 5; retry >= 0; retry--) {      // core.c:4006; Linux retries only on -EAGAIN
        r = fwDownload();
        if (r == kIOReturnSuccess) break;
        IOLog(LOGP "firmware download failed 0x%08x, %d retries left\n", r, retry);
    }
    if (r != kIOReturnSuccess) return r;
    return fwStart();
}

bool RTL8188EUProbe::init(OSDictionary *dict)
{
    IOLog(LOGP "init (personality matched)\n");
    return super::init(dict);
}

IOService *RTL8188EUProbe::probe(IOService *provider, SInt32 *score)
{
    IOLog(LOGP "probe provider=%s\n", provider ? provider->getName() : "(null)");
    return super::probe(provider, score);
}

// Port of rtl8xxxu_init_mac (core.c:2187), RTL8188E branch: 8-bit writes of rtl8188e_mac_init_table
// (terminated by {0xffff,0xff}), then REG_MAX_AGGR_NUM (16-bit) = 0x0707. Stage 3c-1.
IOReturn RTL8188EUProbe::initMac()
{
    for (uint32_t i = 0; ; i++) {
        uint16_t reg = rtl8188e_mac_init_table[i].reg;
        uint8_t  val = rtl8188e_mac_init_table[i].val;
        if (reg == 0xffff && val == 0xff) break;
        IOReturn r = write8(reg, val);
        if (r != kIOReturnSuccess) {
            IOLog(LOGP "initMac: write8(0x%04x, 0x%02x) failed 0x%08x\n", reg, val, r);
            return r;
        }
    }
    return write16(kRegMaxAggrNum, 0x0707);
}

// Port of rtl8xxxu_read_rfreg for RF_A (core.c:867). Same write/delay sequence as Linux.
IOReturn RTL8188EUProbe::rfRead(uint8_t reg, uint32_t *out)
{
    IOReturn r; uint32_t hssia, v;
    if ((r = read32(kRegFpgaXaHssiParm2, &hssia)) != kIOReturnSuccess) return r;
    v = hssia;                                   // path A: val32 = hssia
    v &= ~kHssiParm2AddrMask;
    v |= (uint32_t)reg << kHssiParm2AddrShift;
    v |= kHssiParm2EdgeRead;
    hssia &= ~kHssiParm2EdgeRead;
    if ((r = write32(kRegFpgaXaHssiParm2, hssia)) != kIOReturnSuccess) return r;
    IODelay(10);
    if ((r = write32(kRegFpgaXaHssiParm2, v)) != kIOReturnSuccess) return r;
    IODelay(100);
    hssia |= kHssiParm2EdgeRead;
    if ((r = write32(kRegFpgaXaHssiParm2, hssia)) != kIOReturnSuccess) return r;
    IODelay(10);
    if ((r = read32(kRegFpgaXaHssiParm1, &v)) != kIOReturnSuccess) return r;
    r = read32((v & kFpgaHssiParm1Pi) ? kRegHspiXaReadback : kRegFpgaXaLssiReadback, &v);
    *out = v & 0xfffff;
    return r;
}

// Port of rtl8xxxu_write_rfreg for RF_A (core.c:912); the RTL8192E power-save quirk does not apply.
IOReturn RTL8188EUProbe::rfWrite(uint8_t reg, uint32_t data)
{
    data &= kLssiParmDataMask;
    IOReturn r = write32(kRegFpgaXaLssiParm, ((uint32_t)reg << kLssiParmAddrShift) | data);
    IODelay(1);
    return r;
}

// Port of rtl8xxxu_init_phy_regs (core.c:2228): 32-bit writes, 1 us apart, {0xffff,0xffffffff} terminates.
IOReturn RTL8188EUProbe::initPhyRegs(const Reg32Val *table)
{
    for (uint32_t i = 0; ; i++) {
        if (table[i].reg == 0xffff && table[i].val == 0xffffffff) break;
        IOReturn r = write32(table[i].reg, table[i].val);
        if (r != kIOReturnSuccess) {
            IOLog(LOGP "initPhyRegs: write32(0x%04x, 0x%08x) failed 0x%08x\n", table[i].reg, table[i].val, r);
            return r;
        }
        IODelay(1);
    }
    return kIOReturnSuccess;
}

// Port of rtl8188eu_init_phy_bb (8188e.c:582) plus the 1T1R path of rtl8xxxu_init_phy_bb (core.c:2310):
// the 1T2R patch block and RTL8192E quirk do not apply to the 8188EU; set_crystal_cap is deferred (3c-5).
IOReturn RTL8188EUProbe::initPhyBb()
{
    IOReturn r; uint16_t v16;
    if ((r = read16(kRegSysFunc, &v16)) != kIOReturnSuccess) return r;
    v16 |= kSysFuncBbGlbRstn | kSysFuncBbrstb | kSysFuncDioRf;
    if ((r = write16(kRegSysFunc, v16)) != kIOReturnSuccess) return r;
    if ((r = write8(kRegRfCtrl, kRfEnable | kRfRstb | kRfSdmrstb)) != kIOReturnSuccess) return r;
    // 8-bit write of REG_SYS_FUNC exactly as in 8188e.c:597 (low byte only).
    if ((r = write8(kRegSysFunc, kSysFuncUsba | kSysFuncUsbd | kSysFuncBbGlbRstn | kSysFuncBbrstb)) != kIOReturnSuccess) return r;
    if ((r = initPhyRegs(rtl8188eu_phy_init_table)) != kIOReturnSuccess) return r;
    return initPhyRegs(rtl8188e_agc_table);
}

// Port of rtl8xxxu_init_phy_rf (core.c:2433) for RF_A + rtl8xxxu_init_rf_regs (core.c:2385).
// Table regs 0xf9..0xfe are delay markers (not register writes), {0xff,0xffffffff} terminates.
IOReturn RTL8188EUProbe::initPhyRf()
{
    IOReturn r; uint16_t rfenv, v16; uint32_t v32;
    if ((r = read16(kRegFpgaXaRfSwCtrl, &rfenv)) != kIOReturnSuccess) return r;
    rfenv &= kFpgaRfRfEnv;
    if ((r = read32(kRegFpgaXaRfIntOe, &v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegFpgaXaRfIntOe, v32 | (1u << 20))) != kIOReturnSuccess) return r;
    IODelay(1);
    if ((r = read32(kRegFpgaXaRfIntOe, &v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegFpgaXaRfIntOe, v32 | (1u << 4))) != kIOReturnSuccess) return r;
    IODelay(1);
    if ((r = read32(kRegFpgaXaHssiParm2, &v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegFpgaXaHssiParm2, v32 & ~(uint32_t)kHssi3WireAddrLen)) != kIOReturnSuccess) return r;
    IODelay(1);
    if ((r = read32(kRegFpgaXaHssiParm2, &v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegFpgaXaHssiParm2, v32 & ~(uint32_t)kHssi3WireDataLen)) != kIOReturnSuccess) return r;
    IODelay(1);

    for (uint32_t i = 0; ; i++) {
        uint8_t reg = rtl8188eu_radioa_init_table[i].reg;
        uint32_t val = rtl8188eu_radioa_init_table[i].val;
        if (reg == 0xff && val == 0xffffffff) break;
        switch (reg) {
        case 0xfe: IOSleep(50); continue;
        case 0xfd: IODelay(5000); continue;
        case 0xfc: IODelay(1000); continue;
        case 0xfb: IODelay(50); continue;
        case 0xfa: IODelay(5); continue;
        case 0xf9: IODelay(1); continue;
        }
        if ((r = rfWrite(reg, val)) != kIOReturnSuccess) {
            IOLog(LOGP "initPhyRf: rfWrite(0x%02x, 0x%05x) failed 0x%08x\n", reg, val, r);
            return r;
        }
        IODelay(1);
    }

    if ((r = read16(kRegFpgaXaRfSwCtrl, &v16)) != kIOReturnSuccess) return r;
    v16 &= ~kFpgaRfRfEnv;
    v16 |= rfenv;
    return write16(kRegFpgaXaRfSwCtrl, v16);
}

// Diagnostic only (not in Linux): read back every RF register the table wrote and compare with the LAST value
// written to it (masked to 20 bits). Some RF regs may legitimately read differently; the count is informational.
IOReturn RTL8188EUProbe::rfVerify(uint32_t *checked, uint32_t *mismatch, uint32_t *firstBadReg, uint32_t *firstBadGot)
{
    *checked = 0; *mismatch = 0; *firstBadReg = 0xffff; *firstBadGot = 0;
    for (uint32_t i = 0; ; i++) {
        uint8_t reg = rtl8188eu_radioa_init_table[i].reg;
        uint32_t val = rtl8188eu_radioa_init_table[i].val;
        if (reg == 0xff && val == 0xffffffff) break;
        if (reg >= 0xf9) continue;
        bool last = true;                       // only verify the last write to each register
        for (uint32_t j = i + 1; ; j++) {
            uint8_t r2 = rtl8188eu_radioa_init_table[j].reg;
            if (r2 == 0xff && rtl8188eu_radioa_init_table[j].val == 0xffffffff) break;
            if (r2 == reg) { last = false; break; }
        }
        if (!last) continue;
        uint32_t got = 0;
        IOReturn r = rfRead(reg, &got);
        if (r != kIOReturnSuccess) return r;
        (*checked)++;
        if (got != (val & 0xfffff)) {
            if (*mismatch == 0) { *firstBadReg = reg; *firstBadGot = got; }
            IOLog(LOGP "rf_verify mismatch: reg 0x%02x wrote 0x%05x read 0x%05x xor 0x%05x\n",
                  reg, val & 0xfffff, got, (val & 0xfffff) ^ got);
            (*mismatch)++;
        }
    }
    return kIOReturnSuccess;
}

// rtl8xxxu_llt_write (core.c:2498): write one LLT entry, poll until the op bits go inactive.
IOReturn RTL8188EUProbe::lltWrite(uint8_t address, uint8_t data)
{
    IOReturn r = write32(kRegLltInit, kLltOpWrite | ((uint32_t)address << 8) | data);
    if (r != kIOReturnSuccess) return r;
    uint32_t v = 0;
    int count = 0;
    do {
        if ((r = read32(kRegLltInit, &v)) != kIOReturnSuccess) return r;
        if ((v & kLltOpMask) == 0) return kIOReturnSuccess;     // LLT_OP_INACTIVE
    } while (count++ < kLltPoll);
    return kIOReturnTimeout;                                    // Linux: -EBUSY
}

// rtl8xxxu_init_llt_table (core.c:2519) with 8188e total_page_num=0xa9, last_llt_entry=175.
IOReturn RTL8188EUProbe::initLlt()
{
    IOReturn r;
    const uint8_t lastTxPage = kTxTotalPage8188e;
    for (uint32_t i = 0; i < lastTxPage; i++)
        if ((r = lltWrite((uint8_t)i, (uint8_t)(i + 1))) != kIOReturnSuccess) return r;
    if ((r = lltWrite(lastTxPage, 0xff)) != kIOReturnSuccess) return r;
    for (uint32_t i = lastTxPage + 1; i < kLastLltEntry8188e; i++)       // remaining pages: ring buffer
        if ((r = lltWrite((uint8_t)i, (uint8_t)(i + 1))) != kIOReturnSuccess) return r;
    return lltWrite(kLastLltEntry8188e, lastTxPage + 1);
}

// Port of the part of rtl8xxxu_init_device (core.c:3958) between init_phy_rf and set_tx_power, for the 8188EU
// (fops: has_tx_report, init_reg_pkt_life_time, init_aggregation, no init_reg_rxfltmap/init_burst/init_statistics).
// Deviation (guess): Linux samples "macpower" (CR/SYS_CLKR) before power_on and skips the !macpower blocks
// if the MAC was already up. The probe always ran the full sequence from power_on, so it takes the !macpower path.
// set_tx_power, LEDCFG2/HWSEQ/BAR/GPIO_MUXCFG, LC/IQ calibration are deferred to 3c-5.
IOReturn RTL8188EUProbe::initWmac()
{
    IOReturn r; uint8_t v8; uint16_t v16; uint32_t v32;
#define TRY(x) do { if ((r = (x)) != kIOReturnSuccess) { IOLog(LOGP "initWmac: %s failed 0x%08x (line %d)\n", #x, r, __LINE__); return r; } } while (0)

    // RFSW control (no_pape is never set for 8188EU, so PAPE is included).
    v32 = kFpga0RfTrsw | kFpga0RfTrswb | kFpga0RfAntsw | kFpga0RfAntswb |
          ((kFpga0RfAntsw | kFpga0RfAntswb) << kFpga0RfBdCtrlShift) |
          kFpga0RfPape;
    TRY(write32(kRegFpgaXaRfSwCtrl, v32));

    // TX buffer boundary
    v8 = kTxTotalPage8188e + 1;
    TRY(write8(kRegTxpktbufBcnqBdny, v8));
    TRY(write8(kRegTxpktbufMgqBdny, v8));
    TRY(write8(kRegTxpktbufWmacLbkBfHd, v8));
    TRY(write8(kRegTrxffBndy, v8));
    TRY(write8(kRegTdectrl + 1, v8));

    TRY(write8(kRegPbp, (kPbpPageSize128 << kPbpRxShift) | (kPbpPageSize128 << kPbpTxShift)));

    TRY(initLlt());

    // rtl8188e_usb_quirks (8188e.c:1290) + rtl8xxxu_gen2_usb_quirks (core.c:3782)
    TRY(read16(kRegCr, &v16));
    TRY(write16(kRegCr, v16 | kCrMacTxEnable | kCrMacRxEnable));
    TRY(read32(kRegTxdmaOffsetChk, &v32));
    TRY(write32(kRegTxdmaOffsetChk, v32 | kTxdmaOffsetDropDataEn));
    TRY(write8(kRegEarlyModeControl8188e + 3, 0x01));

    // TX report (has_tx_report, RTL8188E)
    TRY(read8(kRegTxReportCtrl, &v8));
    TRY(write8(kRegTxReportCtrl, v8 | (1u << 0) | kTxReportCtrlTimerEnable));
    TRY(write8(kRegTxReportCtrl + 1, 0x02));
    TRY(write16(kRegTxReportTime, 0xcdf0));
    TRY(read8(0xa3, &v8));
    TRY(write8(0xa3, v8 & 0xf8));

    TRY(write8(kRegRxDrvinfoSz, 4));

    // Interrupts, RTL8188E branch
    TRY(write32(kRegHisr0, 0xffffffff));
    TRY(write32(kRegHimr0, kImr0Pstimeout | kImr0Tbder | kImr0Cpwm | kImr0Cpwm2));
    TRY(write32(kRegHimr1, kImr1Txerr | kImr1Rxerr | kImr1Txfovw | kImr1Rxfovw));
    TRY(read8(kRegUsbSpecialOption, &v8));
    TRY(write8(kRegUsbSpecialOption, v8 | kUsbSpecIntBulkSelect));

    // WMAC: RCR, multicast (init_reg_rxfltmap is not set for 8188EU)
    TRY(write32(kRegRcr, kRcrAcceptPhysMatch | kRcrAcceptMcast | kRcrAcceptBcast | kRcrAcceptMgmtFrame |
                         kRcrHtcLocCtrl | kRcrAppendPhystat | kRcrAppendIcv | kRcrAppendMic));
    TRY(write32(kRegMar, 0xffffffff));
    TRY(write32(kRegMar + 4, 0xffffffff));

    // Adaptive controls
    TRY(read32(kRegResponseRateSet, &v32));
    v32 &= ~(uint32_t)kResponseRateBitmapAll;
    v32 |= kResponseRateRrsrCckOnly1m;
    TRY(write32(kRegResponseRateSet, v32));

    // set_spec_sifs(0x10,0x10); set_retry(0x30,0x30); set_spec_sifs(0x0a,0x10): cck in low byte, ofdm in high byte
    TRY(write16(kRegSpecSifs, (0x10 << 8) | 0x10));
    TRY(write16(kRegRetryLimit, (0x30 << 8) | 0x30));       // short<<8 (mask 0x3f00) | long (mask 0x003f)
    TRY(write16(kRegSpecSifs, (0x10 << 8) | 0x0a));

    // EDCA
    TRY(write16(kRegMacSpecSifs, 0x100a));
    TRY(write16(kRegSifsCck, 0x100a));
    TRY(write16(kRegSifsOfdm, 0x100a));
    TRY(write32(kRegEdcaBe, 0x005ea42b));
    TRY(write32(kRegEdcaBk, 0x0000a44f));
    TRY(write32(kRegEdcaVi, 0x005ea324));
    TRY(write32(kRegEdcaVo, 0x002fa226));

    // Data auto rate fallback retry counts
    TRY(write32(kRegDarfrc, 0x00000000));
    TRY(write32(kRegDarfrc + 4, 0x10080404));
    TRY(write32(kRegRarfrc, 0x04030201));
    TRY(write32(kRegRarfrc + 4, 0x08070605));

    TRY(read8(kRegFwhwTxqCtrl, &v8));
    TRY(write8(kRegFwhwTxqCtrl, v8 | kFwhwTxqCtrlAmpduRetry));
    TRY(write8(kRegAckto, 0x40));

    // Beacon parameters (RTL8188E is not in the exclusion list for REG_DRVERLYINT)
    TRY(write16(kRegBeaconCtrl, kBeaconDisableTsfUpdate | (kBeaconDisableTsfUpdate << 8)));
    TRY(write16(kRegTbttProhibit, 0x6404));
    TRY(write8(kRegDriverEarlyInt, kDriverEarlyIntTime));
    TRY(write8(kRegBeaconDmaTime, kBeaconDmaAtimeIntTime));
    TRY(write16(kRegBeaconTcfg, 0x660F));

    // rtl8188eu_init_aggregation (8188e.c:524)
    TRY(read8(kRegUsbSpecialOption, &v8));
    TRY(write8(kRegUsbSpecialOption, v8 & ~kUsbSpecUsbAggEnable));
    TRY(read8(kRegTrxdmaCtrl, &v8));
    TRY(write8(kRegTrxdmaCtrl, v8 & ~kTrxdmaCtrlRxdmaAggEn));

    // init_reg_pkt_life_time
    TRY(write16(kRegPktVoViLifeTime, 0x0400));
    TRY(write16(kRegPktBeBkLifeTime, 0x0400));

    // Enable CCK and OFDM blocks
    TRY(read32(kRegFpga0RfMode, &v32));
    TRY(write32(kRegFpga0RfMode, v32 | kFpgaRfModeCck | kFpgaRfModeOfdm));

    // Invalidate all CAM entries (bit 30 undocumented)
    TRY(write32(kRegCamCmd, kCamCmdPolling | (1u << 30)));
#undef TRY
    return kIOReturnSuccess;
}

// rtl8188f_set_tx_power (8188f.c:358), which is what rtl8188eu_fops.set_tx_power points to. The 8188EU parse_efuse
// only fills cck_base and ht40_base, so all the *_diff terms stay 0 (priv is zeroed). Channel 1 -> group 0, cck_group 0.
IOReturn RTL8188EUProbe::setTxPower(int channel, bool ht40)
{
    IOReturn r; uint32_t v32;
    int group = channel < 3 ? 0 : channel < 6 ? 1 : channel < 9 ? 2 : channel < 12 ? 3 : 4;
    int cckGroup = (channel == 14) ? 5 : group;
    uint8_t cck = _efuse[kEfuseOffCckBaseA + cckGroup];
    uint8_t ofdmbase = _efuse[kEfuseOffHt40BaseA + group];     // + ofdm_tx_power_diff[0].a == 0
    uint8_t mcsbase = ofdmbase;                                 // + ht{20,40}_tx_power_diff[0].a == 0
    (void)ht40;
    uint32_t ofdm = ofdmbase * 0x01010101u, mcs = mcsbase * 0x01010101u;
    IOLog(LOGP "set_tx_power ch%d: cck=0x%02x ofdm/mcs=0x%02x (efuse)\n", channel, cck, ofdmbase);

    if ((r = read32(kRegTxAgcACck1Mcs32, &v32)) != kIOReturnSuccess) return r;
    v32 = (v32 & 0xffff00ff) | ((uint32_t)cck << 8);
    if ((r = write32(kRegTxAgcACck1Mcs32, v32)) != kIOReturnSuccess) return r;
    if ((r = read32(kRegTxAgcBCck11ACck211, &v32)) != kIOReturnSuccess) return r;
    v32 = (v32 & 0xff) | ((uint32_t)cck << 8) | ((uint32_t)cck << 16) | ((uint32_t)cck << 24);
    if ((r = write32(kRegTxAgcBCck11ACck211, v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegTxAgcARate1806, ofdm)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegTxAgcARate5424, ofdm)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegTxAgcAMcs0300, mcs)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegTxAgcAMcs0704, mcs)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegTxAgcAMcs1108, mcs)) != kIOReturnSuccess) return r;
    return write32(kRegTxAgcAMcs1512, mcs);
}

// rtl8723a_phy_lc_calibrate (core.c:3498), RF path A only (tx_paths == 1; has_s0s1 is not set for 8188EU).
IOReturn RTL8188EUProbe::phyLcCalibrate()
{
    IOReturn r; uint32_t lstf, rfAmode = 0, v32;
    if ((r = read32(kRegOfdm1Lstf, &lstf)) != kIOReturnSuccess) return r;
    bool contTx = (lstf & kOfdmLstfMask) != 0;
    if (contTx) {
        if ((r = write32(kRegOfdm1Lstf, lstf & ~(uint32_t)kOfdmLstfMask)) != kIOReturnSuccess) return r;
        if ((r = rfRead(kRf6052RegAc, &rfAmode)) != kIOReturnSuccess) return r;
        if ((r = rfWrite(kRf6052RegAc, (rfAmode & 0x8ffff) | 0x10000)) != kIOReturnSuccess) return r;
    } else {
        if ((r = write8(kRegTxpause, 0xff)) != kIOReturnSuccess) return r;
    }
    if ((r = rfRead(kRf6052RegModeAg, &v32)) != kIOReturnSuccess) return r;
    if ((r = rfWrite(kRf6052RegModeAg, v32 | 0x08000)) != kIOReturnSuccess) return r;
    IOSleep(100);
    if (contTx) {
        if ((r = write32(kRegOfdm1Lstf, lstf)) != kIOReturnSuccess) return r;
        return rfWrite(kRf6052RegAc, rfAmode);
    }
    return write8(kRegTxpause, 0x00);
}

// Remaining part of rtl8xxxu_init_device (core.c:4283-4440) for the 8188EU, up to (not including) IQ calibration,
// which is deferred (8188e.c:906, ~350 lines, not needed for scan to start), as are set_crystal_cap/CFO tracking and
// the software rate-control init.
IOReturn RTL8188EUProbe::initTail()
{
    IOReturn r; uint8_t v8; uint32_t v32;
#define TRY(x) do { if ((r = (x)) != kIOReturnSuccess) { IOLog(LOGP "initTail: %s failed 0x%08x (line %d)\n", #x, r, __LINE__); return r; } } while (0)
    TRY(setTxPower(1, false));                               // default power, channel 1, 20 MHz
    TRY(read8(kRegLedcfg2, &v8));                            // let the 8051 take antenna control
    TRY(write8(kRegLedcfg2, v8 | kLedcfg2DpdtSelect));
    TRY(write8(kRegHwseqCtrl, 0xff));
    TRY(write32(kRegBarModeCtrl, 0x0201ffff));
    TRY(read8(kRegGpioMuxcfg, &v8));                         // 8188E/F/8192F GPIO init
    TRY(write8(kRegGpioMuxcfg, v8 & ~kGpioMuxcfgIoSelEnbt));
    TRY(phyLcCalibrate());
    // gen2_thermal_meter, chip != 8188F/8710B
    TRY(rfWrite(kRf6052RegTMeter8723b, 0x37cf8));
    TRY(write8(kRegNavUpper, (30000 + kNavUpperUnit - 1) / kNavUpperUnit));
    TRY(write8(kRegUsbHrpwm, 0x00));                         // RTL8192E/RTL8188E
    TRY(read32(kRegFwhwTxqCtrl, &v32));
    TRY(write32(kRegFwhwTxqCtrl, v32 | kFwhwTxqCtrlXmitMgmtAck));
#undef TRY
    return kIOReturnSuccess;
}

bool RTL8188EUProbe::start(IOService *provider)
{
    if (!super::start(provider)) return false;

    IOLog(LOGP "start provider class=%s\n", provider->getMetaClass()->getClassName());
    _iface = OSDynamicCast(IOUSBHostInterface, provider);
    if (!_iface) { IOLog(LOGP "provider is not IOUSBHostInterface\n"); return false; }

    if (!_iface->open(this)) { IOLog(LOGP "open interface failed\n"); return false; }
    _open = true;
    _iface->retain();

    const StandardUSB::InterfaceDescriptor *id = _iface->getInterfaceDescriptor();
    IOLog(LOGP "attached: interface %u class 0x%02x endpoints %u\n",
          id->bInterfaceNumber, id->bInterfaceClass, id->bNumEndpoints);

    // Enumerate endpoints (log only; pipes kept for Stage 2 TX/RX work).
    const StandardUSB::EndpointDescriptor *ep = nullptr;
    while ((ep = (const StandardUSB::EndpointDescriptor *)
            StandardUSB::getNextAssociatedDescriptorWithType(
                _iface->getConfigurationDescriptor(), id,
                (const StandardUSB::Descriptor *)ep, kDescriptorTypeEndpoint)) != nullptr) {
        uint8_t addr = StandardUSB::getEndpointAddress(ep);
        uint8_t dir  = StandardUSB::getEndpointDirection(ep);
        uint8_t type = StandardUSB::getEndpointType(ep);
        IOLog(LOGP "endpoint 0x%02x dir=%s type=%u\n", addr,
              dir == kIOUSBEndpointDirectionIn ? "IN" : "OUT", type);
        if (type != kIOUSBEndpointTypeBulk) continue;
        if (dir == kIOUSBEndpointDirectionIn && !_bulkIn) {
            _bulkIn = _iface->copyPipe(addr);
        } else if (dir == kIOUSBEndpointDirectionOut && _nBulkOut < 4) {
            _bulkOut[_nBulkOut] = _iface->copyPipe(addr);
            if (_bulkOut[_nBulkOut]) _nBulkOut++;
        }
    }
    IOLog(LOGP "bulk IN %s, bulk OUT count %u\n", _bulkIn ? "ok" : "MISSING", _nBulkOut);

    _ctlBuf = IOBufferMemoryDescriptor::inTaskWithOptions(
        kernel_task, kIODirectionInOut, 4, 4);
    _blkBuf = IOBufferMemoryDescriptor::inTaskWithOptions(
        kernel_task, kIODirectionInOut, kWriteNBlock, 4);
    if (!_ctlBuf || !_blkBuf) { closeAll(); return false; }

    // Step 2 of the test protocol: read-only chip identification.
    uint32_t sysCfg = 0;
    IOReturn r = regRead(kRegSysCfg, &sysCfg, sizeof(sysCfg));
    if (r != kIOReturnSuccess) {
        IOLog(LOGP "SYS_CFG read failed: 0x%08x\n", r);
    } else {
        uint32_t cut = (sysCfg & kSysCfgChipVerMask) >> 12;
        IOLog(LOGP "REG_SYS_CFG(0x00f0) = 0x%08x cut=%u%s%s\n", sysCfg, cut,
              (sysCfg & kSysCfgTrpVauxEn) ? " TEST-CHIP(unsupported by rtl8xxxu)" : "",
              cut == 8 ? " CUT-I(unsupported by rtl8xxxu)" : "");
        // Test protocol step 2b: MAC from efuse. Skip on chips rtl8xxxu rejects.
        if (!(sysCfg & kSysCfgTrpVauxEn) && cut != 8) {
            IOReturn er = efuseReadAll();
            if (er != kIOReturnSuccess) IOLog(LOGP "efuse read failed: 0x%08x\n", er);
            else {
                logEfuse();
                // Stage 3b-1: MAC power-on only (no firmware yet).
                IOReturn pr = powerOn();
                uint16_t cr = 0, clkr = 0; uint32_t fsmco = 0;
                read16(kRegCr, &cr); read16(kRegSysClkr, &clkr); read32(kRegApsFsmco, &fsmco);
                IOLog(LOGP "power_on %s (0x%08x): CR=0x%04x SYS_CLKR=0x%04x (MAC_CLK %s) APS_FSMCO=0x%08x\n",
                      pr == kIOReturnSuccess ? "OK" : "FAILED", pr, cr, clkr,
                      (clkr & kSysClkMacClkEnable) ? "on" : "OFF", fsmco);
                if (pr == kIOReturnSuccess) {
                    IOReturn fr = loadFirmware();
                    uint32_t fwdl = 0; read32(kRegMcuFwDl, &fwdl);
                    IOLog(LOGP "firmware %s (0x%08x): FW_DL=0x%08x\n",
                          fr == kIOReturnSuccess ? "RUNNING" : "FAILED", fr, fwdl);
                    if (fr == kIOReturnSuccess) {
                        // Stage 3c-1: MAC register table (Linux order: after firmware start).
                        IOReturn mr = initMac();
                        uint16_t aggr = 0; uint8_t b0 = 0, b1 = 0;
                        read16(kRegMaxAggrNum, &aggr); read8(0x428, &b0); read8(0x652, &b1);
                        IOLog(LOGP "init_mac %s (0x%08x): MAX_AGGR_NUM=0x%04x (expect 0x0707) 0x428=0x%02x (expect 0x0a) 0x652=0x%02x (expect 0x20)\n",
                              mr == kIOReturnSuccess ? "OK" : "FAILED", mr, aggr, b0, b1);
                        if (mr == kIOReturnSuccess) {
                            // Stage 3c-2: BB init + RF accessor check (Linux order: init_mac -> init_phy_bb).
                            IOReturn br = initPhyBb();
                            uint32_t bb800 = 0, bb804 = 0, bb808 = 0, rf00 = 0xdeadbeef;
                            read32(0x800, &bb800); read32(0x804, &bb804); read32(0x808, &bb808);
                            IOReturn rr = rfRead(0x00, &rf00);
                            IOLog(LOGP "init_phy_bb %s (0x%08x): 0x800=0x%08x 0x804=0x%08x 0x808=0x%08x; rf_read(A,0x00) %s 0x%05x (informational, RF not initialised yet)\n",
                                  br == kIOReturnSuccess ? "OK" : "FAILED", br, bb800, bb804, bb808,
                                  rr == kIOReturnSuccess ? "=" : "FAILED", rf00);
                            if (br == kIOReturnSuccess) {
                                // Stage 3c-3: radio A table (Linux order: init_phy_bb -> init_phy_rf).
                                IOReturn fr2 = initPhyRf();
                                uint32_t chk = 0, bad = 0, badReg = 0, badGot = 0;
                                IOReturn vr = (fr2 == kIOReturnSuccess) ? rfVerify(&chk, &bad, &badReg, &badGot) : fr2;
                                IOLog(LOGP "init_phy_rf %s (0x%08x): verify %s: %u regs read back, %u mismatch (first: reg 0x%02x got 0x%05x)\n",
                                      fr2 == kIOReturnSuccess ? "OK" : "FAILED", fr2,
                                      vr == kIOReturnSuccess ? "ok" : "ERROR", chk, bad, badReg, badGot);
                                if (fr2 == kIOReturnSuccess) {
                                    // Stage 3c-4: WMAC/LLT/EDCA/beacon block (Linux order: init_phy_rf -> RFSW ... CAM).
                                    IOReturn wr = initWmac();
                                    uint32_t rcr = 0, llt = 0, cam = 0, sw = 0, edca = 0;
                                    uint16_t cr2 = 0, mx = 0; uint8_t drv = 0, bnd = 0;
                                    read32(kRegRcr, &rcr); read32(kRegLltInit, &llt); read32(kRegCamCmd, &cam);
                                    read32(kRegFpgaXaRfSwCtrl, &sw); read32(kRegEdcaBe, &edca);
                                    read16(kRegCr, &cr2); read8(kRegRxDrvinfoSz, &drv); read8(kRegTrxffBndy, &bnd);
                                    read16(kRegSifsCck, &mx);
                                    IOLog(LOGP "init_wmac %s (0x%08x): CR=0x%04x RCR=0x%08x (expect 0x7000600e) RX_DRVINFO=%u (expect 4) "
                                          "TRXFF_BNDY=0x%02x (expect 0xaa) RFSW=0x%08x (expect 0x07000760) SIFS_CCK=0x%04x (expect 0x100a) "
                                          "EDCA_BE=0x%08x (expect 0x005ea42b) LLT_INIT=0x%08x CAM_CMD=0x%08x\n",
                                          wr == kIOReturnSuccess ? "OK" : "FAILED", wr, cr2, rcr, drv, bnd, sw, mx, edca, llt, cam);
                                    if (wr == kIOReturnSuccess) {
                                        // Stage 3c-5: tx power, LC calibration, thermal meter, NAV etc.
                                        IOReturn tr = initTail();
                                        uint32_t agc = 0, ofdmr = 0, rf18 = 0, rf42 = 0; uint8_t nav = 0, hw = 0;
                                        read32(kRegTxAgcACck1Mcs32, &agc); read32(kRegTxAgcARate1806, &ofdmr);
                                        rfRead(kRf6052RegModeAg, &rf18); rfRead(kRf6052RegTMeter8723b, &rf42);
                                        read8(kRegNavUpper, &nav); read8(kRegHwseqCtrl, &hw);
                                        IOLog(LOGP "init_tail %s (0x%08x): 0xe08=0x%08x 0xe00=0x%08x RF18=0x%05x (LC cal bit15 should be clear) "
                                              "RF42=0x%05x NAV_UPPER=0x%02x (expect 0xeb) HWSEQ=0x%02x (expect 0xff)\n",
                                              tr == kIOReturnSuccess ? "OK" : "FAILED", tr, agc, ofdmr, rf18, rf42, nav, hw);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    registerService();
    return true;
}

bool RTL8188EUProbe::willTerminate(IOService *provider, IOOptionBits options)
{
    // Hot-unplug: end the session so the port can re-enumerate.
    closeAll();
    return super::willTerminate(provider, options);
}

void RTL8188EUProbe::closeAll()
{
    if (_bulkIn) { _bulkIn->abort(); _bulkIn->release(); _bulkIn = nullptr; }
    for (uint32_t i = 0; i < _nBulkOut; i++) {
        if (_bulkOut[i]) { _bulkOut[i]->abort(); _bulkOut[i]->release(); _bulkOut[i] = nullptr; }
    }
    _nBulkOut = 0;
    if (_ctlBuf) { _ctlBuf->release(); _ctlBuf = nullptr; }
    if (_blkBuf) { _blkBuf->release(); _blkBuf = nullptr; }
    if (_iface) {
        if (_open) { _iface->close(this); _open = false; }
        _iface->release();
        _iface = nullptr;
    }
}

void RTL8188EUProbe::stop(IOService *provider)
{
    closeAll();
    super::stop(provider);
}

void RTL8188EUProbe::free()
{
    closeAll();
    super::free();
}
