// SPDX-License-Identifier: GPL-2.0-only
// RTL8188EUCore.cpp — RTL8188EU hardware core (USB transport + init + TX/RX). See header. Register constants are from Linux
// drivers/net/wireless/realtek/rtl8xxxu/{rtl8xxxu.h,regs.h} (verified 2026-10-07).

#include <kern/clock.h>
#include <libkern/OSByteOrder.h>
#include "RTL8188EUCore.hpp"
#include "rtl8188eu_txdesc.h"
#include <IOKit/IOLib.h>
#include <IOKit/usb/StandardUSB.h>
#include "rtl8188eu_fw.h"   // generated by scripts/fetch-rtl8188eu-fw.sh (rtl8188eu_fw[], rtl8188eu_fw_len)
#include "rtl8188eu_tables.h" // generated by scripts/gen-rtl8188eu-tables.py (rtl8188e_mac_init_table[])

#define super OSObject
OSDefineMetaClassAndStructors(RTL8188EUCore, OSObject)

#define LOGP "RTL8188EUProbe: "

enum {
    kRealtekUsbRead   = 0xC0,   // REALTEK_USB_READ
    kRealtekUsbWrite  = 0x40,   // REALTEK_USB_WRITE
    kRealtekUsbCmdReq = 0x05,   // REALTEK_USB_CMD_REQ
    kRegSysCfg        = 0x00F0, // REG_SYS_CFG
    kSysCfgChipVerMask  = 0xF000, // SYS_CFG_CHIP_VERSION_MASK (bits 12-15)
    kSysCfgTrpVauxEn    = 1u << 23, // SYS_CFG_TRP_VAUX_EN (test chip)
    kCtlTimeoutMs     = 500,    // RTW_USB_CONTROL_MSG_TIMEOUT

    // regs.h
    kRegSysIsoCtrl    = 0x0000, kSysIsoPwcEv12v = 1u << 15,
    kRegSysFunc       = 0x0002, kSysFuncEldr    = 1u << 12,
    kRegSysClkr       = 0x0008, kSysClkAna8m    = 1u << 1, kSysClkLoaderEnable = 1u << 5,
    kReg9346Cr        = 0x000A, kEepromBoot     = 1u << 4, kEepromEnable = 1u << 5,
    kRegEfuseCtrl     = 0x0030,
    kRegEfuseAccess   = 0x00CF, kEfuseAccessEnable = 0x69, kEfuseAccessDisable = 0x00,
    // rtl8xxxu.h
    kEfuseMapLen      = 512,    // EFUSE_MAP_LEN == EFUSE_REAL_CONTENT_LEN_8723A
    kEfuseMaxWordUnit = 4,
    kMaxRegPoll       = 500,    // RTL8XXXU_MAX_REG_POLL
    // Stage 3b power_on (8188e.c rtl8188e_disabled_to_emu / emu_to_active / rtl8188eu_power_on)
    kRegApsFsmco      = 0x0004,
    kFsmcoMacEnable   = 1u << 8, kFsmcoHwSuspend = 1u << 11, kFsmcoPcie = 1u << 12,
    kFsmcoHwPowerdown = 1u << 15, kFsmcoPowerReady = 1u << 17,   // BIT(17) written as literal in 8188e.c
    kSysFuncBbrstb    = 1u << 0, kSysFuncBbGlbRstn = 1u << 1,
    kRegAfeXtalCtrl   = 0x0024, kAfeXtalSchmitt = 1u << 23,
    kRegLpldoCtrl     = 0x0023, kLpldoSleep = 1u << 4,
    kRegCr            = 0x0100,
    kRegMaxAggrNum    = 0x04ca,  // REG_MAX_AGGR_NUM (regs.h:634)
    // Stage 3c-2 BB init / RF access (regs.h, verified 2026-10-07)
    kSysFuncUsba = 1u << 2, kSysFuncUsbd = 1u << 4, kSysFuncDioRf = 1u << 13,
    kRegRfCtrl = 0x001f, kRfEnable = 1u << 0, kRfRstb = 1u << 1, kRfSdmrstb = 1u << 2,
    kRegFpgaXaHssiParm1 = 0x0820, kFpgaHssiParm1Pi = 1u << 8,
    kRegFpgaXaHssiParm2 = 0x0824, kHssiParm2AddrShift = 23, kHssiParm2AddrMask = 0x7f800000u,
    kHssiParm2EdgeRead = 1u << 31,
    kRegFpgaXaRfIntOe = 0x0860, kRegFpgaXaRfSwCtrl = 0x0870, kFpgaRfRfEnv = 1u << 4,
    kHssi3WireDataLen = 0x800, kHssi3WireAddrLen = 0x400,
    kRegFpgaXaLssiParm = 0x0840, kLssiParmAddrShift = 20, kLssiParmDataMask = 0x000fffff,
    kRegFpgaXaLssiReadback = 0x08a0, kRegHspiXaReadback = 0x08b8,
    kCrHciTxdma = 1u << 0, kCrHciRxdma = 1u << 1, kCrTxdma = 1u << 2, kCrRxdma = 1u << 3,
    kCrProtocol = 1u << 4, kCrSchedule = 1u << 5, kCrSecurity = 1u << 9, kCrCaltimer = 1u << 10,
    kSysClkMacClkEnable = 1u << 11,
    // Stage 3b-2 firmware (regs.h / rtl8xxxu.h / 8188e.c, verified 2026-10-07)
    kRegMcuFwDl       = 0x0080,
    kFwDlEnable = 1u << 0, kFwDlReady = 1u << 1, kFwDlCsumReport = 1u << 2,
    kFwDlWintInitReady = 1u << 6, kFwDlRamSel = 1u << 7,
    kSysFuncCpuEnable = 1u << 10,
    kRegFwStart       = 0x1000,   // REG_FW_START_ADDRESS
    kFwPageSize       = 4096,     // RTL_FW_PAGE_SIZE
    kFwPollMax        = 1000,     // RTL8XXXU_FIRMWARE_POLL_MAX
    kFwHeaderLen      = 32,       // sizeof(struct rtl8xxxu_firmware_header)
    kWriteNBlock      = 196,      // rtl8188eu_fops.writeN_block_size
    kRegTrxdmaCtrl    = 0x010C,
    kQueueLow = 1, kQueueNormal = 2, kQueueHigh = 3,           // TRXDMA_QUEUE_*
    kRegTrxffBndy     = 0x0114, kTrxffBoundary8188e = 0x25ff,
    kRegRqpn          = 0x0200, kRegRqpnNpq = 0x0214, kRqpnLoad = 1u << 31,
    kTxTotalPage8188e = 0xa9, kTxPageHi8188e = 0x29, kTxPageLo8188e = 0x1c, kTxPageNorm8188e = 0x1c,
    // Stage 3c-4 WMAC/LLT block (regs.h, verified 2026-10-07 against build/src/regs.h)
    kRegLltInit = 0x01e0, kLltOpWrite = 1u << 30, kLltOpMask = 3u << 30, kLltPoll = 20,
    kLastLltEntry8188e = 175,
    kRegTxpktbufBcnqBdny = 0x0424, kRegTxpktbufMgqBdny = 0x0425, kRegTxpktbufWmacLbkBfHd = 0x045d,
    kRegTdectrl = 0x0208, kRegPbp = 0x0104, kPbpPageSize128 = 1, kPbpRxShift = 0, kPbpTxShift = 4,
    kFpga0RfTrsw = 1u << 5, kFpga0RfTrswb = 1u << 6, kFpga0RfAntsw = 1u << 8, kFpga0RfAntswb = 1u << 9,
    kFpga0RfPape = 1u << 10, kFpga0RfBdCtrlShift = 16,
    kCrMacTxEnable = 1u << 6, kCrMacRxEnable = 1u << 7,
    kRegTxdmaOffsetChk = 0x020c, kTxdmaOffsetDropDataEn = 1u << 9,
    kRegEarlyModeControl8188e = 0x04d0,
    kRegTxReportCtrl = 0x04ec, kTxReportCtrlTimerEnable = 1u << 1, kRegTxReportTime = 0x04f0,
    kRegRxDrvinfoSz = 0x060f,
    kRegHisr0 = 0x00b4, kRegHimr0 = 0x00b0, kRegHimr1 = 0x00b8,
    kImr0Pstimeout = 1u << 29, kImr0Tbder = 1u << 26, kImr0Cpwm = 1u << 8, kImr0Cpwm2 = 1u << 9,
    kImr1Txerr = 1u << 11, kImr1Rxerr = 1u << 10, kImr1Txfovw = 1u << 9, kImr1Rxfovw = 1u << 8,
    kRegUsbSpecialOption = 0xfe55, kUsbSpecIntBulkSelect = 1u << 4, kUsbSpecUsbAggEnable = 1u << 3,
    kTrxdmaCtrlRxdmaAggEn = 1u << 2,
    kRegRcr = 0x0608, kRcrAcceptPhysMatch = 1u << 1, kRcrAcceptMcast = 1u << 2, kRcrAcceptBcast = 1u << 3,
    kRcrAcceptMgmtFrame = 1u << 13, kRcrHtcLocCtrl = 1u << 14,
    kRcrAppendPhystat = 1u << 28, kRcrAppendIcv = 1u << 29, kRcrAppendMic = 1u << 30,
    kRegMar = 0x0620,
    kRegResponseRateSet = 0x0440, kResponseRateBitmapAll = 0xfffff, kResponseRateRrsrCckOnly1m = 0xffff1,
    kRegSpecSifs = 0x0428, kRegRetryLimit = 0x042a,
    kRegMacSpecSifs = 0x063a, kRegSifsCck = 0x0514, kRegSifsOfdm = 0x0516,
    kRegEdcaBe = 0x0508, kRegEdcaBk = 0x050c, kRegEdcaVi = 0x0504, kRegEdcaVo = 0x0500,
    kRegDarfrc = 0x0430, kRegRarfrc = 0x0438,
    kRegFwhwTxqCtrl = 0x0420, kFwhwTxqCtrlAmpduRetry = 1u << 7,
    kRegAckto = 0x0640,
    kRegBeaconCtrl = 0x0550, kBeaconDisableTsfUpdate = 1u << 4,
    kRegTbttProhibit = 0x0540, kRegDriverEarlyInt = 0x0558, kDriverEarlyIntTime = 5,
    kRegBeaconDmaTime = 0x0559, kBeaconDmaAtimeIntTime = 2, kRegBeaconTcfg = 0x0510,
    kRegPktVoViLifeTime = 0x04c0, kRegPktBeBkLifeTime = 0x04c2,
    kRegBwOpmode = 0x0603, kBwOpmode20Mhz = 1u << 2, kRegFpga1RfMode = 0x0900,
    kRf6052ModeAgChannelMask = 0x3ff, kRf6052ModeAgBwMask = (1u << 10) | (1u << 11), kRf6052ModeAgBw20Mhz8723b = (1u << 10) | (1u << 11),
    kRegFpga0RfMode = 0x0800, kFpgaRfModeCck = 1u << 24, kFpgaRfModeOfdm = 1u << 25,
    kRegCamCmd = 0x0670, kCamCmdPolling = 1u << 31,
    // Stage 3c-5 tail of init_device (regs.h / rtl8xxxu.h / 8188f.c, verified 2026-10-07)
    kEfuseOffCckBaseA = 0x10, kEfuseOffHt40BaseA = 0x16,        // struct rtl8188eu_efuse.tx_power_index_A
    kRegTxAgcACck1Mcs32 = 0x0e08, kRegTxAgcBCck11ACck211 = 0x086c,
    kRegTxAgcARate1806 = 0x0e00, kRegTxAgcARate5424 = 0x0e04,
    kRegTxAgcAMcs0300 = 0x0e10, kRegTxAgcAMcs0704 = 0x0e14, kRegTxAgcAMcs1108 = 0x0e18, kRegTxAgcAMcs1512 = 0x0e1c,
    kRegLedcfg2 = 0x004e, kLedcfg2DpdtSelect = 1u << 7,
    kRegHwseqCtrl = 0x0423, kRegBarModeCtrl = 0x04cc,
    kRegGpioMuxcfg = 0x0040, kGpioMuxcfgIoSelEnbt = 1u << 5,
    kRegTxpause = 0x0522, kRegOfdm1Lstf = 0x0d00, kOfdmLstfMask = 0x70000000,
    kRf6052RegAc = 0x00, kRf6052RegModeAg = 0x18, kRf6052RegTMeter8723b = 0x42,
    kRegNavUpper = 0x0652, kNavUpperUnit = 128, kRegUsbHrpwm = 0xfe58,
    kFwhwTxqCtrlXmitMgmtAck = 1u << 12,
    // struct rtl8188eu_efuse (rtl8xxxu.h)
    kEfuseRtlId       = 0x8129, kEfuseOffMac = 0xD7,
    // Stage 4b TX. REG_MACID: regs.h:791. txdesc32 bits: rtl8xxxu.h:474-584 (Linux source read 2026-10-07).
    kRegMacid = 0x0610,
    kTxDescSize = 32, kTxQueueMgnt = 0x12,
    kTxdw0Own = 1u << 7, kTxdw0Fs = 1u << 3, kTxdw0Ls = 1u << 2, kTxdw0Bmc = 1u << 0,
    kTxdw2AggBreak = 1u << 16, kTxdw2AntA = 1u << 24, kTxdw2AntB = 1u << 25,
    kTxdw4UseDriverRate = 1u << 8,
    kTxdw5RetryLimitEnable = 1u << 17, kTxdw5RetryLimitShift = 18,
    kTxdw7AntC = (1u << 29) >> 16,
    // Stage 4c link/key registers: regs.h (Linux source read 2026-10-07)
    kRegMsr = 0x0102, kMsrLinkMask = 0x3, kMsrLinkNone = 0, kMsrLinkStation = 2,
    kRegBssid = 0x0618, kRegSlot = 0x051b, kRegBcnMaxErr = 0x055d, kRegBcnPsrRpt = 0x06a8,
    kResponseRateInit2g = 0x15f,
    kRsrAckShortPreamble = 1u << 23, kRegInirtsRateSel = 0x0480,
    kBeaconAtim = 1u << 0, kBeaconFunctionEnable = 1u << 3,
    kRegCamWrite = 0x0674, kCamCmdWrite = 1u << 16, kCamCmdKeyShift = 3, kCamWriteValid = 1u << 15,
    kRegSecurityCfg = 0x0680, kCrSecurityEnable = 1u << 9,
    kSecCfgTxUseDefkey = 1u << 0, kSecCfgRxUseDefkey = 1u << 1, kSecCfgTxSecEnable = 1u << 2,
    kSecCfgRxSecEnable = 1u << 3, kSecCfgTxbcUseDefkey = 1u << 6, kSecCfgRxbcUseDefkey = 1u << 7,
    kRxSlots = 4, kRxBufLen = 4096, kTxSlots = 8, kTxBufLen = 2048,
    kRegHmtfr = 0x01cc, kRegHmbox0 = 0x01d0, kH2cMaxMbox = 4,
    kH2cMediaStatusRpt = 0x01, kH2cRoleAp = 2,     // H2C_8723B_MEDIA_STATUS_RPT, H2C_MACID_ROLE_AP (rtl8xxxu.h:1357,1338)
    kMaxSecCam = 32,                 // fops->max_sec_cam_num for 8188eu
    kCipherCcmpLow = 0x4,            // WLAN_CIPHER_SUITE_CCMP 00-0F-AC:4 & 0x0f (cam_write "hack")
};

IOReturn RTL8188EUCore::regRead(uint16_t addr, void *out, uint16_t len)
{
    if (!_iface || !_ctlBuf || len > 4) return kIOReturnNotReady;
    StandardUSB::DeviceRequest req = {};
    req.bmRequestType = kRealtekUsbRead;
    req.bRequest      = kRealtekUsbCmdReq;
    req.wValue        = addr;   // x86_64 only: host order == USB little-endian
    req.wIndex        = 0;
    req.wLength       = len;
    uint32_t got = 0;
    IOReturn r = _iface->deviceRequest(req, _ctlBuf, got, kCtlTimeoutMs);
    if (r != kIOReturnSuccess) return r;
    if (got != len) return kIOReturnUnderrun;
    bcopy(_ctlBuf->getBytesNoCopy(), out, len);
    return kIOReturnSuccess;
}

IOReturn RTL8188EUCore::regWrite(uint16_t addr, const void *in, uint16_t len)
{
    if (!_iface || !_ctlBuf || len > 4) return kIOReturnNotReady;
    bcopy(in, _ctlBuf->getBytesNoCopy(), len);
    StandardUSB::DeviceRequest req = {};
    req.bmRequestType = kRealtekUsbWrite;
    req.bRequest      = kRealtekUsbCmdReq;
    req.wValue        = addr;
    req.wIndex        = 0;
    req.wLength       = len;
    uint32_t got = 0;
    IOReturn r = _iface->deviceRequest(req, _ctlBuf, got, kCtlTimeoutMs);
    if (r != kIOReturnSuccess) return r;
    return got == len ? kIOReturnSuccess : kIOReturnUnderrun;
}

// Port of rtl8xxxu_read_efuse8 (core.c): select offset, clear bit 31 of ctrl+3,
// poll ctrl bit 31 for completion, then data is in the low byte.
IOReturn RTL8188EUCore::efuseRead8(uint16_t offset, uint8_t *data)
{
    uint8_t v8; uint32_t v32 = 0; IOReturn r;

    if ((r = write8(kRegEfuseCtrl + 1, offset & 0xff)) != kIOReturnSuccess) return r;
    if ((r = read8(kRegEfuseCtrl + 2, &v8)) != kIOReturnSuccess) return r;
    v8 = (v8 & 0xfc) | ((offset >> 8) & 0x03);
    if ((r = write8(kRegEfuseCtrl + 2, v8)) != kIOReturnSuccess) return r;

    if ((r = read8(kRegEfuseCtrl + 3, &v8)) != kIOReturnSuccess) return r;
    if ((r = write8(kRegEfuseCtrl + 3, v8 & 0x7f)) != kIOReturnSuccess) return r;

    int i;
    for (i = 0; i < kMaxRegPoll; i++) {
        if ((r = read32(kRegEfuseCtrl, &v32)) != kIOReturnSuccess) return r;
        if (v32 & (1u << 31)) break;
    }
    if (i == kMaxRegPoll) return kIOReturnTimeout;

    IODelay(50);
    if ((r = read32(kRegEfuseCtrl, &v32)) != kIOReturnSuccess) return r;
    *data = v32 & 0xff;
    return kIOReturnSuccess;
}

// Port of rtl8xxxu_read_efuse (core.c). is_multi_func branch omitted: it is not
// set for the 8188EU (assumption: not verified against 8188e.c fops).
// Writes only the efuse access/power/clock enables, exactly as Linux does before power-on.
IOReturn RTL8188EUCore::efuseReadAll()
{
    IOReturn r;
    uint16_t v16;

    if ((r = read16(kReg9346Cr, &v16)) != kIOReturnSuccess) return r;
    IOLog(LOGP "9346CR=0x%04x boot=%s%s\n", v16, (v16 & kEepromBoot) ? "EEPROM" : "EFUSE",
          (v16 & kEepromEnable) ? " (EEPROM present)" : "");

    memset(_efuse, 0xff, sizeof(_efuse));
    if ((r = write8(kRegEfuseAccess, kEfuseAccessEnable)) != kIOReturnSuccess) return r;

    do {
        if ((r = read16(kRegSysIsoCtrl, &v16)) != kIOReturnSuccess) break;
        if (!(v16 & kSysIsoPwcEv12v) &&
            (r = write16(kRegSysIsoCtrl, v16 | kSysIsoPwcEv12v)) != kIOReturnSuccess) break;

        if ((r = read16(kRegSysFunc, &v16)) != kIOReturnSuccess) break;
        if (!(v16 & kSysFuncEldr) &&
            (r = write16(kRegSysFunc, v16 | kSysFuncEldr)) != kIOReturnSuccess) break;

        if ((r = read16(kRegSysClkr, &v16)) != kIOReturnSuccess) break;
        uint16_t need = kSysClkLoaderEnable | kSysClkAna8m;
        if ((v16 & need) != need &&
            (r = write16(kRegSysClkr, v16 | need)) != kIOReturnSuccess) break;

        uint16_t addr = 0;
        while (addr < kEfuseMapLen) {
            uint8_t header, ext, val8;
            uint16_t offset, mask;
            if ((r = efuseRead8(addr++, &header)) != kIOReturnSuccess) break;
            if (header == 0xff) break;
            if ((header & 0x1f) == 0x0f) {              // extended header
                offset = (header & 0xe0) >> 5;
                if ((r = efuseRead8(addr++, &ext)) != kIOReturnSuccess) break;
                if ((ext & 0x0f) == 0x0f) continue;     // all words disabled
                offset |= (ext & 0xf0) >> 1;
                mask = ext & 0x0f;
            } else {
                offset = (header >> 4) & 0x0f;
                mask = header & 0x0f;
            }
            uint16_t map = offset * 8;
            for (int i = 0; i < kEfuseMaxWordUnit; i++) {
                if (mask & (1u << i)) { map += 2; continue; }
                if ((r = efuseRead8(addr++, &val8)) != kIOReturnSuccess) break;
                if (map >= kEfuseMapLen - 1) { IOLog(LOGP "illegal efuse map_addr 0x%04x\n", map); r = kIOReturnBadArgument; break; }
                _efuse[map++] = val8;
                if ((r = efuseRead8(addr++, &val8)) != kIOReturnSuccess) break;
                _efuse[map++] = val8;
            }
            if (r != kIOReturnSuccess) break;
        }
    } while (0);

    write8(kRegEfuseAccess, kEfuseAccessDisable);   // always restore
    return r;
}

void RTL8188EUCore::logEfuse()
{
    uint16_t id = (uint16_t)(_efuse[0] | (_efuse[1] << 8));
    const uint8_t *m = &_efuse[kEfuseOffMac];
    IOLog(LOGP "efuse rtl_id=0x%04x (%s, expect 0x%04x)\n", id,
          id == kEfuseRtlId ? "OK" : "MISMATCH", kEfuseRtlId);
    IOLog(LOGP "efuse MAC %02x:%02x:%02x:%02x:%02x:%02x\n", m[0], m[1], m[2], m[3], m[4], m[5]);
    for (int row = 0; row < 16; row++) {
        const uint8_t *b = &_efuse[row * 16];
        IOLog(LOGP "efuse[%03x] %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x\n",
              row * 16, b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7],
              b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15]);
    }
}

// Port of rtl8188eu_power_on (8188e.c). Does NOT touch TX/RX MAC enable (hw bug note in source).
IOReturn RTL8188EUCore::powerOn()
{
    uint16_t v16; uint32_t v32 = 0; uint8_t v8;
    IOReturn r;
    #define TRY(x) do { r = (x); if (r != kIOReturnSuccess) { IOLog(LOGP "powerOn: %s failed 0x%08x\n", #x, r); return r; } } while (0)

    // rtl8188e_disabled_to_emu
    TRY(read16(kRegApsFsmco, &v16));
    v16 &= ~(kFsmcoHwSuspend | kFsmcoPcie);
    TRY(write16(kRegApsFsmco, v16));

    // rtl8188e_emu_to_active: wait 0x04[17] power ready
    int count;
    for (count = kMaxRegPoll; count; count--) {
        TRY(read32(kRegApsFsmco, &v32));
        if (v32 & kFsmcoPowerReady) break;
        IODelay(10);
    }
    if (!count) { IOLog(LOGP "powerOn: power-ready (0x04[17]) timeout, FSMCO=0x%08x\n", v32); return kIOReturnTimeout; }

    TRY(read8(kRegSysFunc, &v8));                       // reset baseband
    v8 &= ~(kSysFuncBbrstb | kSysFuncBbGlbRstn);
    TRY(write8(kRegSysFunc, v8));

    TRY(read32(kRegAfeXtalCtrl, &v32));                 // schmitt trigger
    v32 |= kAfeXtalSchmitt;
    TRY(write32(kRegAfeXtalCtrl, v32));

    TRY(read16(kRegApsFsmco, &v16));                    // disable HWPDN
    v16 &= ~kFsmcoHwPowerdown;
    TRY(write16(kRegApsFsmco, v16));

    TRY(read16(kRegApsFsmco, &v16));                    // disable WL suspend
    v16 &= ~(kFsmcoHwSuspend | kFsmcoPcie);
    TRY(write16(kRegApsFsmco, v16));

    TRY(read32(kRegApsFsmco, &v32));                    // set MAC_ENABLE, poll until it clears
    v32 |= kFsmcoMacEnable;
    TRY(write32(kRegApsFsmco, v32));
    for (count = kMaxRegPoll; count; count--) {
        TRY(read32(kRegApsFsmco, &v32));
        if (!(v32 & kFsmcoMacEnable)) break;
        IODelay(10);
    }
    if (!count) { IOLog(LOGP "powerOn: MAC_ENABLE did not clear, FSMCO=0x%08x\n", v32); return kIOReturnTimeout; }

    TRY(read8(kRegLpldoCtrl, &v8));                     // LDO normal mode
    v8 &= ~kLpldoSleep;
    TRY(write8(kRegLpldoCtrl, v8));

    v16 = kCrHciTxdma | kCrHciRxdma | kCrTxdma | kCrRxdma |
          kCrProtocol | kCrSchedule | kCrSecurity | kCrCaltimer;
    TRY(write16(kRegCr, v16));
    #undef TRY
    return kIOReturnSuccess;
}

// Port of rtl8xxxu_writeN: control writes of at most 196 bytes, wValue advancing per chunk.
IOReturn RTL8188EUCore::regWriteN(uint16_t addr, const uint8_t *buf, uint32_t len)
{
    if (!_iface || !_blkBuf) return kIOReturnNotReady;
    while (len) {
        uint32_t n = len > kWriteNBlock ? kWriteNBlock : len;
        bcopy(buf, _blkBuf->getBytesNoCopy(), n);
        StandardUSB::DeviceRequest req = {};
        req.bmRequestType = kRealtekUsbWrite;
        req.bRequest      = kRealtekUsbCmdReq;
        req.wValue        = addr;
        req.wIndex        = 0;
        req.wLength       = (uint16_t)n;
        uint32_t got = 0;
        IOReturn r = _iface->deviceRequest(req, _blkBuf, got, kCtlTimeoutMs);
        if (r != kIOReturnSuccess || got != n) {
            IOLog(LOGP "writeN failed at 0x%04x len %u: 0x%08x got %u\n", addr, n, r, got);
            return r != kIOReturnSuccess ? r : kIOReturnUnderrun;
        }
        addr += n; buf += n; len -= n;
    }
    return kIOReturnSuccess;
}

// Ports of rtl8xxxu_init_queue_reserved_page (core.c:3815), rtl8xxxu_init_queue_priority (core.c:2580,
// cases 2 and 3) and the REG_TRXFF_BNDY+2 write, in the order of core.c:3990-4001.
// 8188eu uses config_endpoints_no_sie (8188e.c:418, core.c:1717): 1st OUT ep = high, 2nd = normal,
// 3rd+ = low. The user's dongle has 2 bulk OUT (0x02, 0x03) => high + normal, no low queue.
// GUESS: Linux skips the reserved-page write if the MAC was already powered before power_on;
// we always write it (fresh plug assumed).
IOReturn RTL8188EUCore::initQueues()
{
    IOReturn r;
    if (_nBulkOut != 2 && _nBulkOut != 3) {
        IOLog(LOGP "initQueues: unsupported bulk OUT count %u (handled: 2, 3)\n", _nBulkOut);
        return kIOReturnUnsupported;
    }
    const bool hasLow = (_nBulkOut == 3);

    uint32_t hq = kTxPageHi8188e, lq = hasLow ? kTxPageLo8188e : 0, nq = kTxPageNorm8188e;
    uint32_t pubq = kTxTotalPage8188e - hq - lq - nq - 1;
    if ((r = write32(kRegRqpnNpq, (nq << 0) | (0u << 16))) != kIOReturnSuccess) return r;
    if ((r = write32(kRegRqpn, kRqpnLoad | (hq << 0) | (lq << 8) | (pubq << 16))) != kIOReturnSuccess) return r;

    // core.c case 3: VO,MG,HI=high VI=normal BE,BK=low. case 2 (high+normal): VO,VI,MG,HI=high BE,BK=normal.
    const uint16_t voq = kQueueHigh, miq = kQueueHigh;
    const uint16_t viq = hasLow ? kQueueNormal : kQueueHigh;
    const uint16_t beq = hasLow ? kQueueLow : kQueueNormal;
    IOLog(LOGP "initQueues: %u bulk OUT, %s low queue\n", _nBulkOut, hasLow ? "with" : "no");

    uint16_t v16;
    if ((r = read16(kRegTrxdmaCtrl, &v16)) != kIOReturnSuccess) return r;
    v16 &= 0x7;
    v16 |= (voq << 4) | (viq << 6) | (beq << 8) | (beq << 10) | (miq << 12) | (miq << 14);   // VO VI BE BK MG HI
    if ((r = write16(kRegTrxdmaCtrl, v16)) != kIOReturnSuccess) return r;

    return write16(kRegTrxffBndy + 2, kTrxffBoundary8188e);
}

// rtl8188eu_reset_8051 (8188e.c:558)
IOReturn RTL8188EUCore::reset8051()
{
    uint16_t sf; IOReturn r;
    if ((r = read16(kRegSysFunc, &sf)) != kIOReturnSuccess) return r;
    sf &= ~kSysFuncCpuEnable;
    if ((r = write16(kRegSysFunc, sf)) != kIOReturnSuccess) return r;
    sf |= kSysFuncCpuEnable;
    return write16(kRegSysFunc, sf);
}

// Port of rtl8xxxu_download_firmware (core.c:2004), payload = blob minus 32-byte header.
IOReturn RTL8188EUCore::fwDownload()
{
    #define TRY(x) do { r = (x); if (r != kIOReturnSuccess) { IOLog(LOGP "fwDownload: %s failed 0x%08x\n", #x, r); goto abort; } } while (0)
    IOReturn r; uint8_t v8; uint16_t v16; uint32_t v32;
    const uint8_t *fw = rtl8188eu_fw + kFwHeaderLen;
    uint32_t size = rtl8188eu_fw_len - kFwHeaderLen, pages = size / kFwPageSize, rem = size % kFwPageSize, i;

    TRY(read8(kRegSysFunc + 1, &v8));  TRY(write8(kRegSysFunc + 1, v8 | 4));
    TRY(read16(kRegSysFunc, &v16));    TRY(write16(kRegSysFunc, v16 | kSysFuncCpuEnable));

    TRY(read8(kRegMcuFwDl, &v8));
    if (v8 & kFwDlRamSel) {
        IOLog(LOGP "firmware already running, resetting MCU\n");
        TRY(write8(kRegMcuFwDl, 0x00));
        TRY(reset8051());
    }
    TRY(read8(kRegMcuFwDl, &v8));      TRY(write8(kRegMcuFwDl, v8 | kFwDlEnable));
    TRY(read32(kRegMcuFwDl, &v32));    TRY(write32(kRegMcuFwDl, v32 & ~(1u << 19)));   // 8051 reset
    TRY(read8(kRegMcuFwDl, &v8));      TRY(write8(kRegMcuFwDl, v8 | kFwDlCsumReport)); // reset checksum

    for (i = 0; i < pages; i++) {
        TRY(read8(kRegMcuFwDl + 2, &v8));
        TRY(write8(kRegMcuFwDl + 2, (uint8_t)((v8 & 0xF8) | i)));
        TRY(regWriteN(kRegFwStart, fw, kFwPageSize));
        fw += kFwPageSize;
    }
    if (rem) {
        TRY(read8(kRegMcuFwDl + 2, &v8));
        TRY(write8(kRegMcuFwDl + 2, (uint8_t)((v8 & 0xF8) | i)));
        TRY(regWriteN(kRegFwStart, fw, rem));
    }
    r = kIOReturnSuccess;
abort:
    // always: MCU firmware download disable (16-bit)
    if (read16(kRegMcuFwDl, &v16) == kIOReturnSuccess) write16(kRegMcuFwDl, v16 & ~kFwDlEnable);
    return r;
    #undef TRY
}

// Port of rtl8xxxu_start_firmware (core.c:1944). 8188eu: no HMTFR write (init_reg_hmtfr unset).
IOReturn RTL8188EUCore::fwStart()
{
    uint32_t v32 = 0; IOReturn r; int i;
    for (i = 0; i < kFwPollMax; i++) {
        if ((r = read32(kRegMcuFwDl, &v32)) != kIOReturnSuccess) return r;
        if (v32 & kFwDlCsumReport) break;
    }
    if (i == kFwPollMax) { IOLog(LOGP "firmware checksum poll timed out, FW_DL=0x%08x\n", v32); return kIOReturnTimeout; }

    if ((r = read32(kRegMcuFwDl, &v32)) != kIOReturnSuccess) return r;
    v32 |= kFwDlReady; v32 &= ~kFwDlWintInitReady;
    if ((r = write32(kRegMcuFwDl, v32)) != kIOReturnSuccess) return r;
    if ((r = reset8051()) != kIOReturnSuccess) return r;

    for (i = 0; i < kFwPollMax; i++) {
        if ((r = read32(kRegMcuFwDl, &v32)) != kIOReturnSuccess) return r;
        if (v32 & kFwDlWintInitReady) break;
        IODelay(100);
    }
    if (i == kFwPollMax) { IOLog(LOGP "firmware failed to start, FW_DL=0x%08x\n", v32); return kIOReturnTimeout; }
    return kIOReturnSuccess;
}

IOReturn RTL8188EUCore::loadFirmware()
{
    if (rtl8188eu_fw_len <= kFwHeaderLen) return kIOReturnBadArgument;
    uint16_t sig = rtl8188eu_fw[0] | (rtl8188eu_fw[1] << 8);
    switch (sig & 0xfff0) {   // core.c:2140 accepted signatures
    case 0x92e0: case 0x92c0: case 0x88e0: case 0x88c0: case 0x5300:
    case 0x2300: case 0x88f0: case 0x10b0: case 0x92f0: break;
    default: IOLog(LOGP "invalid firmware signature 0x%04x\n", sig); return kIOReturnBadArgument;
    }
    IOLog(LOGP "firmware %u bytes, revision %u.%u signature 0x%04x\n", rtl8188eu_fw_len,
          rtl8188eu_fw[4] | (rtl8188eu_fw[5] << 8), rtl8188eu_fw[6], sig);

    IOReturn r = initQueues();
    if (r != kIOReturnSuccess) { IOLog(LOGP "initQueues failed 0x%08x\n", r); return r; }

    for (int retry = 5; retry >= 0; retry--) {      // core.c:4006; Linux retries only on -EAGAIN
        r = fwDownload();
        if (r == kIOReturnSuccess) break;
        IOLog(LOGP "firmware download failed 0x%08x, %d retries left\n", r, retry);
    }
    if (r != kIOReturnSuccess) return r;
    return fwStart();
}

bool RTL8188EUCore::init()
{
    return super::init();
}

// Port of rtl8xxxu_init_mac (core.c:2187), RTL8188E branch: 8-bit writes of rtl8188e_mac_init_table
// (terminated by {0xffff,0xff}), then REG_MAX_AGGR_NUM (16-bit) = 0x0707. Stage 3c-1.
IOReturn RTL8188EUCore::initMac()
{
    for (uint32_t i = 0; ; i++) {
        uint16_t reg = rtl8188e_mac_init_table[i].reg;
        uint8_t  val = rtl8188e_mac_init_table[i].val;
        if (reg == 0xffff && val == 0xff) break;
        IOReturn r = write8(reg, val);
        if (r != kIOReturnSuccess) {
            IOLog(LOGP "initMac: write8(0x%04x, 0x%02x) failed 0x%08x\n", reg, val, r);
            return r;
        }
    }
    return write16(kRegMaxAggrNum, 0x0707);
}

// Port of rtl8xxxu_read_rfreg for RF_A (core.c:867). Same write/delay sequence as Linux.
IOReturn RTL8188EUCore::rfRead(uint8_t reg, uint32_t *out)
{
    IOReturn r; uint32_t hssia, v;
    if ((r = read32(kRegFpgaXaHssiParm2, &hssia)) != kIOReturnSuccess) return r;
    v = hssia;                                   // path A: val32 = hssia
    v &= ~kHssiParm2AddrMask;
    v |= (uint32_t)reg << kHssiParm2AddrShift;
    v |= kHssiParm2EdgeRead;
    hssia &= ~kHssiParm2EdgeRead;
    if ((r = write32(kRegFpgaXaHssiParm2, hssia)) != kIOReturnSuccess) return r;
    IODelay(10);
    if ((r = write32(kRegFpgaXaHssiParm2, v)) != kIOReturnSuccess) return r;
    IODelay(100);
    hssia |= kHssiParm2EdgeRead;
    if ((r = write32(kRegFpgaXaHssiParm2, hssia)) != kIOReturnSuccess) return r;
    IODelay(10);
    if ((r = read32(kRegFpgaXaHssiParm1, &v)) != kIOReturnSuccess) return r;
    r = read32((v & kFpgaHssiParm1Pi) ? kRegHspiXaReadback : kRegFpgaXaLssiReadback, &v);
    *out = v & 0xfffff;
    return r;
}

// Port of rtl8xxxu_write_rfreg for RF_A (core.c:912); the RTL8192E power-save quirk does not apply.
IOReturn RTL8188EUCore::rfWrite(uint8_t reg, uint32_t data)
{
    data &= kLssiParmDataMask;
    IOReturn r = write32(kRegFpgaXaLssiParm, ((uint32_t)reg << kLssiParmAddrShift) | data);
    IODelay(1);
    return r;
}

// Port of rtl8xxxu_init_phy_regs (core.c:2228): 32-bit writes, 1 us apart, {0xffff,0xffffffff} terminates.
IOReturn RTL8188EUCore::initPhyRegs(const Reg32Val *table)
{
    for (uint32_t i = 0; ; i++) {
        if (table[i].reg == 0xffff && table[i].val == 0xffffffff) break;
        IOReturn r = write32(table[i].reg, table[i].val);
        if (r != kIOReturnSuccess) {
            IOLog(LOGP "initPhyRegs: write32(0x%04x, 0x%08x) failed 0x%08x\n", table[i].reg, table[i].val, r);
            return r;
        }
        IODelay(1);
    }
    return kIOReturnSuccess;
}

// Port of rtl8188eu_init_phy_bb (8188e.c:582) plus the 1T1R path of rtl8xxxu_init_phy_bb (core.c:2310):
// the 1T2R patch block and RTL8192E quirk do not apply to the 8188EU; set_crystal_cap is deferred (3c-5).
IOReturn RTL8188EUCore::initPhyBb()
{
    IOReturn r; uint16_t v16;
    if ((r = read16(kRegSysFunc, &v16)) != kIOReturnSuccess) return r;
    v16 |= kSysFuncBbGlbRstn | kSysFuncBbrstb | kSysFuncDioRf;
    if ((r = write16(kRegSysFunc, v16)) != kIOReturnSuccess) return r;
    if ((r = write8(kRegRfCtrl, kRfEnable | kRfRstb | kRfSdmrstb)) != kIOReturnSuccess) return r;
    // 8-bit write of REG_SYS_FUNC exactly as in 8188e.c:597 (low byte only).
    if ((r = write8(kRegSysFunc, kSysFuncUsba | kSysFuncUsbd | kSysFuncBbGlbRstn | kSysFuncBbrstb)) != kIOReturnSuccess) return r;
    if ((r = initPhyRegs(rtl8188eu_phy_init_table)) != kIOReturnSuccess) return r;
    return initPhyRegs(rtl8188e_agc_table);
}

// Port of rtl8xxxu_init_phy_rf (core.c:2433) for RF_A + rtl8xxxu_init_rf_regs (core.c:2385).
// Table regs 0xf9..0xfe are delay markers (not register writes), {0xff,0xffffffff} terminates.
IOReturn RTL8188EUCore::initPhyRf()
{
    IOReturn r; uint16_t rfenv, v16; uint32_t v32;
    if ((r = read16(kRegFpgaXaRfSwCtrl, &rfenv)) != kIOReturnSuccess) return r;
    rfenv &= kFpgaRfRfEnv;
    if ((r = read32(kRegFpgaXaRfIntOe, &v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegFpgaXaRfIntOe, v32 | (1u << 20))) != kIOReturnSuccess) return r;
    IODelay(1);
    if ((r = read32(kRegFpgaXaRfIntOe, &v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegFpgaXaRfIntOe, v32 | (1u << 4))) != kIOReturnSuccess) return r;
    IODelay(1);
    if ((r = read32(kRegFpgaXaHssiParm2, &v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegFpgaXaHssiParm2, v32 & ~(uint32_t)kHssi3WireAddrLen)) != kIOReturnSuccess) return r;
    IODelay(1);
    if ((r = read32(kRegFpgaXaHssiParm2, &v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegFpgaXaHssiParm2, v32 & ~(uint32_t)kHssi3WireDataLen)) != kIOReturnSuccess) return r;
    IODelay(1);

    for (uint32_t i = 0; ; i++) {
        uint8_t reg = rtl8188eu_radioa_init_table[i].reg;
        uint32_t val = rtl8188eu_radioa_init_table[i].val;
        if (reg == 0xff && val == 0xffffffff) break;
        switch (reg) {
        case 0xfe: IOSleep(50); continue;
        case 0xfd: IODelay(5000); continue;
        case 0xfc: IODelay(1000); continue;
        case 0xfb: IODelay(50); continue;
        case 0xfa: IODelay(5); continue;
        case 0xf9: IODelay(1); continue;
        }
        if ((r = rfWrite(reg, val)) != kIOReturnSuccess) {
            IOLog(LOGP "initPhyRf: rfWrite(0x%02x, 0x%05x) failed 0x%08x\n", reg, val, r);
            return r;
        }
        IODelay(1);
    }

    if ((r = read16(kRegFpgaXaRfSwCtrl, &v16)) != kIOReturnSuccess) return r;
    v16 &= ~kFpgaRfRfEnv;
    v16 |= rfenv;
    return write16(kRegFpgaXaRfSwCtrl, v16);
}

// Diagnostic only (not in Linux): read back every RF register the table wrote and compare with the LAST value
// written to it (masked to 20 bits). Some RF regs may legitimately read differently; the count is informational.
IOReturn RTL8188EUCore::rfVerify(uint32_t *checked, uint32_t *mismatch, uint32_t *firstBadReg, uint32_t *firstBadGot)
{
    *checked = 0; *mismatch = 0; *firstBadReg = 0xffff; *firstBadGot = 0;
    for (uint32_t i = 0; ; i++) {
        uint8_t reg = rtl8188eu_radioa_init_table[i].reg;
        uint32_t val = rtl8188eu_radioa_init_table[i].val;
        if (reg == 0xff && val == 0xffffffff) break;
        if (reg >= 0xf9) continue;
        bool last = true;                       // only verify the last write to each register
        for (uint32_t j = i + 1; ; j++) {
            uint8_t r2 = rtl8188eu_radioa_init_table[j].reg;
            if (r2 == 0xff && rtl8188eu_radioa_init_table[j].val == 0xffffffff) break;
            if (r2 == reg) { last = false; break; }
        }
        if (!last) continue;
        uint32_t got = 0;
        IOReturn r = rfRead(reg, &got);
        if (r != kIOReturnSuccess) return r;
        (*checked)++;
        if (got != (val & 0xfffff)) {
            if (*mismatch == 0) { *firstBadReg = reg; *firstBadGot = got; }
            IOLog(LOGP "rf_verify mismatch: reg 0x%02x wrote 0x%05x read 0x%05x xor 0x%05x\n",
                  reg, val & 0xfffff, got, (val & 0xfffff) ^ got);
            (*mismatch)++;
        }
    }
    return kIOReturnSuccess;
}

// rtl8xxxu_llt_write (core.c:2498): write one LLT entry, poll until the op bits go inactive.
IOReturn RTL8188EUCore::lltWrite(uint8_t address, uint8_t data)
{
    IOReturn r = write32(kRegLltInit, kLltOpWrite | ((uint32_t)address << 8) | data);
    if (r != kIOReturnSuccess) return r;
    uint32_t v = 0;
    int count = 0;
    do {
        if ((r = read32(kRegLltInit, &v)) != kIOReturnSuccess) return r;
        if ((v & kLltOpMask) == 0) return kIOReturnSuccess;     // LLT_OP_INACTIVE
    } while (count++ < kLltPoll);
    return kIOReturnTimeout;                                    // Linux: -EBUSY
}

// rtl8xxxu_init_llt_table (core.c:2519) with 8188e total_page_num=0xa9, last_llt_entry=175.
IOReturn RTL8188EUCore::initLlt()
{
    IOReturn r;
    const uint8_t lastTxPage = kTxTotalPage8188e;
    for (uint32_t i = 0; i < lastTxPage; i++)
        if ((r = lltWrite((uint8_t)i, (uint8_t)(i + 1))) != kIOReturnSuccess) return r;
    if ((r = lltWrite(lastTxPage, 0xff)) != kIOReturnSuccess) return r;
    for (uint32_t i = lastTxPage + 1; i < kLastLltEntry8188e; i++)       // remaining pages: ring buffer
        if ((r = lltWrite((uint8_t)i, (uint8_t)(i + 1))) != kIOReturnSuccess) return r;
    return lltWrite(kLastLltEntry8188e, lastTxPage + 1);
}

// Port of the part of rtl8xxxu_init_device (core.c:3958) between init_phy_rf and set_tx_power, for the 8188EU
// (fops: has_tx_report, init_reg_pkt_life_time, init_aggregation, no init_reg_rxfltmap/init_burst/init_statistics).
// Deviation (guess): Linux samples "macpower" (CR/SYS_CLKR) before power_on and skips the !macpower blocks
// if the MAC was already up. The probe always ran the full sequence from power_on, so it takes the !macpower path.
// set_tx_power, LEDCFG2/HWSEQ/BAR/GPIO_MUXCFG, LC/IQ calibration are deferred to 3c-5.
IOReturn RTL8188EUCore::initWmac()
{
    IOReturn r; uint8_t v8; uint16_t v16; uint32_t v32;
#define TRY(x) do { if ((r = (x)) != kIOReturnSuccess) { IOLog(LOGP "initWmac: %s failed 0x%08x (line %d)\n", #x, r, __LINE__); return r; } } while (0)

    // RFSW control (no_pape is never set for 8188EU, so PAPE is included).
    v32 = kFpga0RfTrsw | kFpga0RfTrswb | kFpga0RfAntsw | kFpga0RfAntswb |
          ((kFpga0RfAntsw | kFpga0RfAntswb) << kFpga0RfBdCtrlShift) |
          kFpga0RfPape | (kFpga0RfPape << kFpga0RfBdCtrlShift);
    TRY(write32(kRegFpgaXaRfSwCtrl, v32));

    // TX buffer boundary
    v8 = kTxTotalPage8188e + 1;
    TRY(write8(kRegTxpktbufBcnqBdny, v8));
    TRY(write8(kRegTxpktbufMgqBdny, v8));
    TRY(write8(kRegTxpktbufWmacLbkBfHd, v8));
    TRY(write8(kRegTrxffBndy, v8));
    TRY(write8(kRegTdectrl + 1, v8));

    TRY(write8(kRegPbp, (kPbpPageSize128 << kPbpRxShift) | (kPbpPageSize128 << kPbpTxShift)));

    TRY(initLlt());

    // rtl8188e_usb_quirks (8188e.c:1290) + rtl8xxxu_gen2_usb_quirks (core.c:3782)
    TRY(read16(kRegCr, &v16));
    TRY(write16(kRegCr, v16 | kCrMacTxEnable | kCrMacRxEnable));
    TRY(read32(kRegTxdmaOffsetChk, &v32));
    TRY(write32(kRegTxdmaOffsetChk, v32 | kTxdmaOffsetDropDataEn));
    TRY(write8(kRegEarlyModeControl8188e + 3, 0x01));

    // TX report (has_tx_report, RTL8188E)
    TRY(read8(kRegTxReportCtrl, &v8));
    TRY(write8(kRegTxReportCtrl, v8 | (1u << 0) | kTxReportCtrlTimerEnable));
    TRY(write8(kRegTxReportCtrl + 1, 0x02));
    TRY(write16(kRegTxReportTime, 0xcdf0));
    TRY(read8(0xa3, &v8));
    TRY(write8(0xa3, v8 & 0xf8));

    TRY(write8(kRegRxDrvinfoSz, 4));

    // Interrupts, RTL8188E branch
    TRY(write32(kRegHisr0, 0xffffffff));
    TRY(write32(kRegHimr0, kImr0Pstimeout | kImr0Tbder | kImr0Cpwm | kImr0Cpwm2));
    TRY(write32(kRegHimr1, kImr1Txerr | kImr1Rxerr | kImr1Txfovw | kImr1Rxfovw));
    TRY(read8(kRegUsbSpecialOption, &v8));
    TRY(write8(kRegUsbSpecialOption, v8 | kUsbSpecIntBulkSelect));

    // WMAC: RCR, multicast (init_reg_rxfltmap is not set for 8188EU)
    TRY(write32(kRegRcr, kRcrAcceptPhysMatch | kRcrAcceptMcast | kRcrAcceptBcast | kRcrAcceptMgmtFrame |
                         kRcrHtcLocCtrl | kRcrAppendPhystat | kRcrAppendIcv | kRcrAppendMic));
    TRY(write32(kRegMar, 0xffffffff));
    TRY(write32(kRegMar + 4, 0xffffffff));

    // Adaptive controls
    TRY(read32(kRegResponseRateSet, &v32));
    v32 &= ~(uint32_t)kResponseRateBitmapAll;
    v32 |= kResponseRateRrsrCckOnly1m;
    TRY(write32(kRegResponseRateSet, v32));

    // set_spec_sifs(0x10,0x10); set_retry(0x30,0x30); set_spec_sifs(0x0a,0x10): cck in low byte, ofdm in high byte
    TRY(write16(kRegSpecSifs, (0x10 << 8) | 0x10));
    TRY(write16(kRegRetryLimit, (0x30 << 8) | 0x30));       // short<<8 (mask 0x3f00) | long (mask 0x003f)
    TRY(write16(kRegSpecSifs, (0x10 << 8) | 0x0a));

    // EDCA
    TRY(write16(kRegMacSpecSifs, 0x100a));
    TRY(write16(kRegSifsCck, 0x100a));
    TRY(write16(kRegSifsOfdm, 0x100a));
    TRY(write32(kRegEdcaBe, 0x005ea42b));
    TRY(write32(kRegEdcaBk, 0x0000a44f));
    TRY(write32(kRegEdcaVi, 0x005ea324));
    TRY(write32(kRegEdcaVo, 0x002fa226));

    // Data auto rate fallback retry counts
    TRY(write32(kRegDarfrc, 0x00000000));
    TRY(write32(kRegDarfrc + 4, 0x10080404));
    TRY(write32(kRegRarfrc, 0x04030201));
    TRY(write32(kRegRarfrc + 4, 0x08070605));

    TRY(read8(kRegFwhwTxqCtrl, &v8));
    TRY(write8(kRegFwhwTxqCtrl, v8 | kFwhwTxqCtrlAmpduRetry));
    TRY(write8(kRegAckto, 0x40));

    // Beacon parameters (RTL8188E is not in the exclusion list for REG_DRVERLYINT)
    TRY(write16(kRegBeaconCtrl, kBeaconDisableTsfUpdate | (kBeaconDisableTsfUpdate << 8)));
    TRY(write16(kRegTbttProhibit, 0x6404));
    TRY(write8(kRegDriverEarlyInt, kDriverEarlyIntTime));
    TRY(write8(kRegBeaconDmaTime, kBeaconDmaAtimeIntTime));
    TRY(write16(kRegBeaconTcfg, 0x660F));

    // rtl8188eu_init_aggregation (8188e.c:524)
    TRY(read8(kRegUsbSpecialOption, &v8));
    TRY(write8(kRegUsbSpecialOption, v8 & ~kUsbSpecUsbAggEnable));
    TRY(read8(kRegTrxdmaCtrl, &v8));
    TRY(write8(kRegTrxdmaCtrl, v8 & ~kTrxdmaCtrlRxdmaAggEn));

    // init_reg_pkt_life_time
    TRY(write16(kRegPktVoViLifeTime, 0x0400));
    TRY(write16(kRegPktBeBkLifeTime, 0x0400));

    // Enable CCK and OFDM blocks
    TRY(read32(kRegFpga0RfMode, &v32));
    TRY(write32(kRegFpga0RfMode, v32 | kFpgaRfModeCck | kFpgaRfModeOfdm));

    // Invalidate all CAM entries (bit 30 undocumented)
    TRY(write32(kRegCamCmd, kCamCmdPolling | (1u << 30)));
#undef TRY
    return kIOReturnSuccess;
}

// rtl8188f_set_tx_power (8188f.c:358), which is what rtl8188eu_fops.set_tx_power points to. The 8188EU parse_efuse
// only fills cck_base and ht40_base, so all the *_diff terms stay 0 (priv is zeroed). Channel 1 -> group 0, cck_group 0.
IOReturn RTL8188EUCore::setTxPower(int channel, bool ht40)
{
    IOReturn r; uint32_t v32;
    int group = channel < 3 ? 0 : channel < 6 ? 1 : channel < 9 ? 2 : channel < 12 ? 3 : 4;
    int cckGroup = (channel == 14) ? 5 : group;
    uint8_t cck = _efuse[kEfuseOffCckBaseA + cckGroup];
    uint8_t ofdmbase = _efuse[kEfuseOffHt40BaseA + group];     // + ofdm_tx_power_diff[0].a == 0
    uint8_t mcsbase = ofdmbase;                                 // + ht{20,40}_tx_power_diff[0].a == 0
    (void)ht40;
    uint32_t ofdm = ofdmbase * 0x01010101u, mcs = mcsbase * 0x01010101u;
    IOLog(LOGP "set_tx_power ch%d: cck=0x%02x ofdm/mcs=0x%02x (efuse)\n", channel, cck, ofdmbase);

    if ((r = read32(kRegTxAgcACck1Mcs32, &v32)) != kIOReturnSuccess) return r;
    v32 = (v32 & 0xffff00ff) | ((uint32_t)cck << 8);
    if ((r = write32(kRegTxAgcACck1Mcs32, v32)) != kIOReturnSuccess) return r;
    if ((r = read32(kRegTxAgcBCck11ACck211, &v32)) != kIOReturnSuccess) return r;
    v32 = (v32 & 0xff) | ((uint32_t)cck << 8) | ((uint32_t)cck << 16) | ((uint32_t)cck << 24);
    if ((r = write32(kRegTxAgcBCck11ACck211, v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegTxAgcARate1806, ofdm)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegTxAgcARate5424, ofdm)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegTxAgcAMcs0300, mcs)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegTxAgcAMcs0704, mcs)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegTxAgcAMcs1108, mcs)) != kIOReturnSuccess) return r;
    return write32(kRegTxAgcAMcs1512, mcs);
}

// rtl8723a_phy_lc_calibrate (core.c:3498), RF path A only (tx_paths == 1; has_s0s1 is not set for 8188EU).
// Stage 3d: rtl8188eu_config_channel (8188e.c:423), 20 MHz only (width 20/20_NOHT branch). 40 MHz is NOT ported yet.
// Unlike gen1/gen2 it does not touch SIFS/ANALOG2. rf_paths == 1 for 8188EU, so only path A.
IOReturn RTL8188EUCore::setChannel(int channel)
{
    IOReturn r; uint8_t opmode; uint32_t v32;
    if (channel < 1 || channel > 14) return kIOReturnBadArgument;
    if ((r = setTxPower(channel, false)) != kIOReturnSuccess) return r;   // Linux order: set_tx_power, then config_channel (core.c:6838-6840)
    if ((r = read8(kRegBwOpmode, &opmode)) != kIOReturnSuccess) return r;
    if ((r = write8(kRegBwOpmode, opmode | kBwOpmode20Mhz)) != kIOReturnSuccess) return r;
    if ((r = read32(kRegFpga0RfMode, &v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegFpga0RfMode, v32 & ~1u)) != kIOReturnSuccess) return r;      // ~FPGA_RF_MODE
    if ((r = read32(kRegFpga1RfMode, &v32)) != kIOReturnSuccess) return r;
    if ((r = write32(kRegFpga1RfMode, v32 & ~1u)) != kIOReturnSuccess) return r;
    if ((r = rfRead(kRf6052RegModeAg, &v32)) != kIOReturnSuccess) return r;
    v32 = (v32 & ~kRf6052ModeAgChannelMask) | (uint32_t)channel;
    if ((r = rfWrite(kRf6052RegModeAg, v32)) != kIOReturnSuccess) return r;
    if ((r = rfRead(kRf6052RegModeAg, &v32)) != kIOReturnSuccess) return r;
    v32 = (v32 & ~kRf6052ModeAgBwMask) | kRf6052ModeAgBw20Mhz8723b;
    if ((r = rfWrite(kRf6052RegModeAg, v32)) != kIOReturnSuccess) return r;
    return kIOReturnSuccess;
}


// Stage 4b: REG_MACID <- efuse MAC (Linux does this in add_interface -> rtl8xxxu_set_mac, port 0, core.c:3558).
IOReturn RTL8188EUCore::setMacAddr()
{
    IOReturn r;
    for (int i = 0; i < 6; i++)
        if ((r = write8(kRegMacid + i, _efuse[kEfuseOffMac + i])) != kIOReturnSuccess) return r;
    return kIOReturnSuccess;
}

// Stage 4b: send one management frame (rate 1M, broadcast/multicast per DA) on the MGNT queue.
// Port of rtl8xxxu_tx (core.c:5456) + rtl8xxxu_fill_txdesc_v3 (core.c:5378) for the mgmt, non-QoS, no-key, no-AMPDU case.
// With 2 bulk OUT eps (high+normal) MGNT maps to pipe index 0 (init_queue_priority case 2, mgp = 0) => _bulkOut[0].
// 8188e rate-adaptation / tx-report handling is NOT ported; the TX report (C2H) is ignored.
IOReturn RTL8188EUCore::fillTxDesc(uint8_t *d, const uint8_t *frame, uint16_t len, uint16_t seq)
{
    // Delegates to the host-tested builder (tools/test_txdesc.cpp proves byte-identity with the previous inline version).
    rtl8188eu_tx::Params p = { rtl8188eu_tx::kQueueMgnt, 0, rtl8188eu_tx::kSecNone, false, false, false, 0xff, (int32_t)(seq & 0xfff) };
    rtl8188eu_tx::build(d, frame, len, p);
    return kIOReturnSuccess;
}

IOReturn RTL8188EUCore::txMgmt(IOBufferMemoryDescriptor *buf, const uint8_t *frame, uint16_t len, uint16_t seq)
{
    if (!_bulkOut[0]) return kIOReturnNotReady;
    if (len < 24 || kTxDescSize + len > buf->getLength()) return kIOReturnBadArgument;
    fillTxDesc((uint8_t *)buf->getBytesNoCopy(), frame, len, seq);
    uint32_t sent = 0;
    return _bulkOut[0]->io(buf, kTxDescSize + len, sent, 500);
}

// ---- Stage 4d: asynchronous TX/RX engine (foundation for the frontend shim). Not hardware-tested yet. ----

// Async TX of one frame (any type). Slot pool of kTxSlots; the completion releases the slot and calls _txDoneCb.
// Queue/pipe selection follows rtl8xxxu_queue_select + init_queue_priority (see rtl8188eu_txdesc.h). Data-frame rate is
// supplied by the caller (no rate adaptation yet). Port of rtl8xxxu_tx. Not hardware-tested for data frames.
IOReturn RTL8188EUCore::txSubmitFrame(const uint8_t *frame, uint16_t len, const rtl8188eu_tx::Params &p, void *cookie)
{
    if (!_asyncUp) return kIOReturnNotReady;
    if (len < 24 || kTxDescSize + len > kTxBufLen) return kIOReturnBadArgument;
    int pipe = rtl8188eu_tx::pipeForQueue(p.queue, _nBulkOut);
    if (pipe < 0 || !_bulkOut[pipe]) return kIOReturnNotReady;
    int idx = -1;
    for (int i = 0; i < kTxSlots; i++) {
        if (!(OSBitOrAtomic(1u << i, &_txBusyMask) & (1u << i))) { idx = i; break; }      // returns the old value
    }
    if (idx < 0) return kIOReturnNoResources;
    TxSlot &t = _tx[idx];
    t.cookie = cookie;
    uint32_t total = rtl8188eu_tx::build((uint8_t *)t.buf->getBytesNoCopy(), frame, len, p);
    IOUSBHostCompletion c = { this, &RTL8188EUCore::txCompleteTramp, &t };
    OSIncrementAtomic((volatile SInt32 *)&_stTxSubmitted);
    IOReturn r = _bulkOut[pipe]->io(t.buf, total, &c, 1000);
    if (r != kIOReturnSuccess) {
        OSIncrementAtomic((volatile SInt32 *)&_stTxErrors);
        OSBitAndAtomic(~(1u << idx), &_txBusyMask);
    }
    return r;
}

// Management-frame convenience (MGNT queue, 1M, fixed seq): unchanged behavior for the probe self-tests.
IOReturn RTL8188EUCore::txSubmitMgmt(const uint8_t *frame, uint16_t len, uint16_t seq, void *cookie)
{
    rtl8188eu_tx::Params p = { rtl8188eu_tx::kQueueMgnt, 0, rtl8188eu_tx::kSecNone, false, false, false, 0xff, (int32_t)(seq & 0xfff) };
    return txSubmitFrame(frame, len, p, cookie);
}

void RTL8188EUCore::txCompleteTramp(void *owner, void *param, IOReturn status, uint32_t bytes)
{
    RTL8188EUCore *self = (RTL8188EUCore *)owner; TxSlot *t = (TxSlot *)param;
    OSIncrementAtomic((volatile SInt32 *)&self->_stTxCompleted);
    if (status != kIOReturnSuccess) OSIncrementAtomic((volatile SInt32 *)&self->_stTxErrors);
    void *cookie = t->cookie; t->cookie = nullptr;
    OSBitAndAtomic(~(1u << (t - self->_tx)), &self->_txBusyMask);
    if (self->_txDoneCb) self->_txDoneCb(self->_cbCtx, cookie, status);
}

// Parse one bulk IN buffer (rxdesc16, no aggregation); same layout as rxScan. Returns false if there is no 802.11 frame.
bool RTL8188EUCore::parseRx(const uint8_t *b, uint32_t got, RxInfo *out)
{
    out->frame = nullptr; out->len = 0; out->crcBad = false; out->c2h = false; out->decrypted = false;
    if (got < 24) return false;
    const uint32_t dw0 = OSReadLittleInt32(b, 0), dw3 = OSReadLittleInt32(b, 12);
    uint32_t pktLen = dw0 & 0x3fff, drv = ((dw0 >> 16) & 0xf) * 8, shift = (dw0 >> 24) & 3;
    if (((dw3 >> 14) & 3) != 0) { out->c2h = true; return false; }
    if (dw0 & (1u << 14)) { out->crcBad = true; return false; }
    uint32_t off = 24 + drv + shift;
    if (pktLen < 10 || off + pktLen > got) return false;
    out->frame = b + off; out->len = pktLen;
    // rtl8xxxu_rxdesc16: security = dw0[22:20], swdec = dw0[27]; core.c:6405 sets RX_FLAG_DECRYPTED when !swdec && security != 0.
    out->decrypted = !(dw0 & (1u << 27)) && ((dw0 >> 20) & 7) != 0;
    return true;
}

void RTL8188EUCore::rxCompleteTramp(void *owner, void *param, IOReturn status, uint32_t bytes)
{
    RTL8188EUCore *self = (RTL8188EUCore *)owner; RxSlot *slot = (RxSlot *)param;
    OSIncrementAtomic((volatile SInt32 *)&self->_stRxCompleted);
    if (status == kIOReturnSuccess) {
        self->_rxConsecErr = 0;
        RxInfo ri;
        OSIncrementAtomic((volatile SInt32 *)&self->_stRxBuffers);
        if (self->parseRx((const uint8_t *)slot->buf->getBytesNoCopy(), bytes, &ri)) {
            OSIncrementAtomic((volatile SInt32 *)&self->_stRxFrames);
            // v0.15.0 diagnostic: does any data frame (EAPOL M1) reach the host? Log the first few headers.
            if (ri.len >= 24 && (ri.frame[0] & 0x0c) == 0x08) {
                static volatile SInt32 nData;
                SInt32 n = OSIncrementAtomic(&nData);
                if (n < 12)
                    IOLog(LOGP "rx DATA #%d: fc=%02x%02x len=%u a1=%02x:%02x:%02x:%02x:%02x:%02x a2=%02x:%02x:%02x:%02x:%02x:%02x dec=%d\n",
                          (int)n, ri.frame[0], ri.frame[1], ri.len,
                          ri.frame[4], ri.frame[5], ri.frame[6], ri.frame[7], ri.frame[8], ri.frame[9],
                          ri.frame[10], ri.frame[11], ri.frame[12], ri.frame[13], ri.frame[14], ri.frame[15], (int)ri.decrypted);
            }
            if (self->_rxCbEx) self->_rxCbEx(self->_cbCtx, ri.frame, ri.len, ri.decrypted);
            else if (self->_rxCb) self->_rxCb(self->_cbCtx, ri.frame, ri.len);
        } else if (ri.crcBad) OSIncrementAtomic((volatile SInt32 *)&self->_stRxCrcBad);
        else if (ri.c2h) OSIncrementAtomic((volatile SInt32 *)&self->_stRxC2h);
    } else if (status != kIOReturnAborted) {
        OSIncrementAtomic((volatile SInt32 *)&self->_stRxErrors);
        self->_rxConsecErr++;
    }
    if (self->_rxRunning && status != kIOReturnAborted && self->_rxConsecErr < 16) {
        IOUSBHostCompletion c = { self, &RTL8188EUCore::rxCompleteTramp, slot };
        if (self->_bulkIn->io(slot->buf, kRxBufLen, &c, 0) == kIOReturnSuccess) { OSIncrementAtomic((volatile SInt32 *)&self->_stRxSubmitted); return; }
        OSIncrementAtomic((volatile SInt32 *)&self->_stRxErrors);
    }
    OSDecrementAtomic(&self->_rxOutstanding);
}

IOReturn RTL8188EUCore::asyncStart()
{
    if (_asyncUp) return kIOReturnSuccess;
    if (!_bulkIn) return kIOReturnNotReady;
    for (int i = 0; i < kRxSlots; i++) {
        _rx[i].buf = IOBufferMemoryDescriptor::inTaskWithOptions(kernel_task, kIODirectionIn, kRxBufLen, 4);
        if (!_rx[i].buf) { asyncStop(); return kIOReturnNoMemory; }
    }
    for (int i = 0; i < kTxSlots; i++) {
        _tx[i].buf = IOBufferMemoryDescriptor::inTaskWithOptions(kernel_task, kIODirectionOut, kTxBufLen, 4);
        if (!_tx[i].buf) { asyncStop(); return kIOReturnNoMemory; }
    }
    _asyncUp = true;
    return kIOReturnSuccess;
}

IOReturn RTL8188EUCore::rxStart()
{
    if (!_asyncUp) return kIOReturnNotReady;
    if (_rxRunning) return kIOReturnSuccess;
    {   // v0.15.0 diagnostic: RX data-frame filter maps (0x6a0 mgmt, 0x6a2 ctrl, 0x6a4 data) as left by init.
        uint16_t f0 = 0, f1 = 0, f2 = 0;
        read16(0x06a0, &f0); read16(0x06a2, &f1); read16(0x06a4, &f2);
        IOLog(LOGP "rx_start: RXFLTMAP0=0x%04x RXFLTMAP1=0x%04x RXFLTMAP2=0x%04x\n", f0, f1, f2);
    }
    _rxRunning = 1; _rxConsecErr = 0;
    for (int i = 0; i < kRxSlots; i++) {
        IOUSBHostCompletion c = { this, &RTL8188EUCore::rxCompleteTramp, &_rx[i] };
        OSIncrementAtomic(&_rxOutstanding);
        IOReturn r = _bulkIn->io(_rx[i].buf, kRxBufLen, &c, 0);
        if (r != kIOReturnSuccess) { OSDecrementAtomic(&_rxOutstanding); if (i == 0) { _rxRunning = 0; return r; } }
        else OSIncrementAtomic((volatile SInt32 *)&_stRxSubmitted);
    }
    return kIOReturnSuccess;
}

void RTL8188EUCore::rxStop()
{
    if (!_rxRunning && _rxOutstanding == 0) return;
    _rxRunning = 0;
    if (_bulkIn) _bulkIn->abort();
    for (int i = 0; i < 100 && _rxOutstanding > 0; i++) IOSleep(10);   // wait for aborted completions (max 1 s)
    if (_rxOutstanding > 0) IOLog(LOGP "rx_stop: %d RX completion(s) still outstanding after 1 s\n", (int)_rxOutstanding);
}

void RTL8188EUCore::asyncStop()
{
    rxStop();
    for (int i = 0; i < 100 && _txBusyMask; i++) IOSleep(10);          // let TX completions drain
    if (_txBusyMask) {
        for (uint32_t i = 0; i < _nBulkOut; i++) if (_bulkOut[i]) _bulkOut[i]->abort();
        for (int i = 0; i < 100 && _txBusyMask; i++) IOSleep(10);
    }
    _asyncUp = false;
    for (int i = 0; i < kRxSlots; i++) if (_rx[i].buf) { _rx[i].buf->release(); _rx[i].buf = nullptr; }
    for (int i = 0; i < kTxSlots; i++) if (_tx[i].buf) { _tx[i].buf->release(); _tx[i].buf = nullptr; }
}

// Probe-time test of the async engine: 2 s of RX on ch11, counting beacons of the AP seen earlier, then 5 async probe requests.
struct AsyncTestCtx { volatile SInt32 beacons, probeResp, probeRespToUs, mgmt, txDone, haveBssid, deauthToUs, ackSeen; uint8_t mac[6]; uint8_t bssid[6]; };
static void asyncTestRx(void *ctx, const uint8_t *f, uint32_t len)
{
    AsyncTestCtx *c = (AsyncTestCtx *)ctx;
    if (len < 24) return;
    uint8_t t = f[0] & 0xfc;
    if (t == 0x80) {
        OSIncrementAtomic(&c->beacons);
        if (!c->haveBssid) { memcpy(c->bssid, f + 16, 6); c->haveBssid = 1; }      // addr3 of a beacon = BSSID (first AP heard on ch11)
    }
    else if ((t == 0xc0 || t == 0xa0) && memcmp(f + 4, c->mac, 6) == 0 && c->haveBssid && memcmp(f + 10, c->bssid, 6) == 0)
        OSIncrementAtomic(&c->deauthToUs);                                         // deauth/disassoc from that AP to us (reply to our class-3 data frame)
    else if (t == 0x50) {
        OSIncrementAtomic(&c->probeResp);
        if (memcmp(f + 4, c->mac, 6) == 0) OSIncrementAtomic(&c->probeRespToUs);   // addr1 == our MAC: proves our probe request reached the AP
    }
    if ((f[0] & 0x0c) == 0) OSIncrementAtomic(&c->mgmt);
}
static void asyncTestTxDone(void *ctx, void *cookie, IOReturn st) { OSIncrementAtomic(&((AsyncTestCtx *)ctx)->txDone); }

void RTL8188EUCore::asyncSelfTest()
{
    AsyncTestCtx ctx = {};
    memcpy(ctx.mac, _efuse + kEfuseOffMac, 6);
    IOReturn ra = asyncStart();
    if (ra != kIOReturnSuccess) { IOLog(LOGP "async_selftest: asyncStart FAILED 0x%08x\n", ra); return; }
    IOReturn rc = setChannel(11);
    _cbCtx = &ctx; _rxCb = asyncTestRx; _txDoneCb = asyncTestTxDone;
    _stRxSubmitted = _stRxCompleted = _stRxBuffers = _stRxFrames = _stRxCrcBad = _stRxC2h = _stRxErrors = 0;
    _stTxSubmitted = _stTxCompleted = _stTxErrors = 0;
    IOReturn rr = rxStart();
    IOSleep(2000);
    SInt32 passive = ctx.beacons;
    // 5 async probe requests, broadcast wildcard, 200 ms apart, ch11 only (same IE set as rxScan)
    uint8_t pr[64]; uint16_t n = 0;
    pr[n++] = 0x40; pr[n++] = 0; pr[n++] = 0; pr[n++] = 0;
    for (int i = 0; i < 6; i++) pr[n++] = 0xff;
    for (int i = 0; i < 6; i++) pr[n++] = _efuse[kEfuseOffMac + i];
    for (int i = 0; i < 6; i++) pr[n++] = 0xff;
    uint16_t seqPos = n; n += 2;
    pr[n++] = 0; pr[n++] = 0;
    const uint8_t rates[] = {0x82, 0x84, 0x8b, 0x96, 0x0c, 0x12, 0x18, 0x24};
    pr[n++] = 1; pr[n++] = sizeof(rates); memcpy(pr + n, rates, sizeof(rates)); n += sizeof(rates);
    pr[n++] = 3; pr[n++] = 1; pr[n++] = 11;
    IOReturn lastTx = kIOReturnSuccess;
    for (int i = 0; i < 5; i++) {
        uint16_t sq = (uint16_t)(100 + i);
        pr[seqPos] = (uint8_t)((sq << 4) & 0xff); pr[seqPos + 1] = (uint8_t)((sq << 4) >> 8);
        IOReturn tr = txSubmitMgmt(pr, n, sq, nullptr);
        if (tr != kIOReturnSuccess) lastTx = tr;
        IOSleep(200);
    }
    // v0.14.0 data txdesc check: 5 unassociated Null / QoS-Null data frames (to-DS) to the AP learned from its beacons.
    // An AP that gets a class-3 frame from a non-associated STA normally answers deauth/disassoc to our MAC; that proves the
    // data txdesc (BE queue -> pipe 1, QoS bit, seq from header, 6M driver rate) was accepted by the MAC and transmitted.
    // No reply is INCONCLUSIVE, not a failure (some APs ignore Null frames); tx completions still prove the USB path.
    IOReturn dataTx = kIOReturnSuccess; int dataSent = 0;
    if (ctx.haveBssid) {
        for (int i = 0; i < 5; i++) {
            bool qos = (i >= 3);
            uint8_t df[26]; memset(df, 0, sizeof df);
            df[0] = qos ? 0xc8 : 0x48; df[1] = 0x01;                          // QoS-Null / Null, to-DS
            memcpy(df + 4, ctx.bssid, 6); memcpy(df + 10, ctx.mac, 6); memcpy(df + 16, ctx.bssid, 6);
            uint16_t sq = (uint16_t)(200 + i);
            df[22] = (uint8_t)((sq << 4) & 0xff); df[23] = (uint8_t)((sq << 4) >> 8);
            rtl8188eu_tx::Params p = { rtl8188eu_tx::selectQueue(df, 2 /* IEEE80211_AC_BE */), rtl8188eu_tx::kRate6M,
                                       rtl8188eu_tx::kSecNone, false, false, false, 0xff, -1 };
            IOReturn tr = txSubmitFrame(df, qos ? 26 : 24, p, nullptr);
            if (tr != kIOReturnSuccess) dataTx = tr; else dataSent++;
            IOSleep(200);
        }
        IOSleep(300);
    }
    rxStop();
    IOLog(LOGP "data_selftest: bssid=%02x:%02x:%02x:%02x:%02x:%02x (%s) sent=%d submit_err=0x%x | deauth/disassoc_to_us=%d "
          "(>0 proves data txdesc over the air; 0 = inconclusive) tx_total submitted=%u completed=%u errors=%u\n",
          ctx.bssid[0], ctx.bssid[1], ctx.bssid[2], ctx.bssid[3], ctx.bssid[4], ctx.bssid[5], ctx.haveBssid ? "learned" : "NO BEACON HEARD",
          dataSent, dataTx, (int)ctx.deauthToUs, (unsigned)_stTxSubmitted, (unsigned)_stTxCompleted, (unsigned)_stTxErrors);
    IOLog(LOGP "async_selftest: start=0x%x chan11=0x%x rx_start=0x%x | 2 s passive: beacons=%d (expect ~19 for one AP at 102 ms) | "
          "rx submitted=%u completed=%u buffers=%u frames=%u crc_bad=%u c2h=%u errors=%u | "
          "tx submitted=%u completed=%u errors=%u last_submit=0x%x | probe_resp=%d (to_us=%d, >0 proves TX over the air) mgmt=%d tx_done_cb=%d\n",
          ra, rc, rr, (int)passive, (unsigned)_stRxSubmitted, (unsigned)_stRxCompleted, (unsigned)_stRxBuffers, (unsigned)_stRxFrames,
          (unsigned)_stRxCrcBad, (unsigned)_stRxC2h, (unsigned)_stRxErrors, (unsigned)_stTxSubmitted, (unsigned)_stTxCompleted,
          (unsigned)_stTxErrors, lastTx, (int)ctx.probeResp, (int)ctx.probeRespToUs, (int)ctx.mgmt, (int)ctx.txDone);
    _rxCb = nullptr; _txDoneCb = nullptr; _cbCtx = nullptr;
}


// ---- Stage 4c: link-layer register programming, ports of the corresponding rtl8xxxu pieces (core.c line refs). ----
// None of this is exercised by a hardware test yet; H2C commands (report_connect, update_rate_mask) are NOT ported.

// rtl8xxxu_set_linktype, port 0 (core.c:1589).
IOReturn RTL8188EUCore::setLinkType(uint8_t type)
{
    uint8_t v; IOReturn r = read8(kRegMsr, &v);
    if (r != kIOReturnSuccess) return r;
    return write8(kRegMsr, (uint8_t)((v & 0x0c) | (type & kMsrLinkMask)));
}

// rtl8xxxu_set_bssid, port 0 (core.c:3581).
IOReturn RTL8188EUCore::setBssid(const uint8_t *bssid)
{
    IOReturn r;
    for (int i = 0; i < 6; i++)
        if ((r = write8(kRegBssid + i, bssid[i])) != kIOReturnSuccess) return r;
    return kIOReturnSuccess;
}

// rtl8xxxu_stop_tx_beacon (core.c:1133).
IOReturn RTL8188EUCore::stopTxBeacon()
{
    uint8_t v; IOReturn r;
    if ((r = read8(kRegFwhwTxqCtrl + 2, &v)) != kIOReturnSuccess) return r;
    if ((r = write8(kRegFwhwTxqCtrl + 2, v & ~(1u << 6))) != kIOReturnSuccess) return r;
    if ((r = write8(kRegTbttProhibit + 1, 0x64)) != kIOReturnSuccess) return r;
    if ((r = read8(kRegTbttProhibit + 2, &v)) != kIOReturnSuccess) return r;
    return write8(kRegTbttProhibit + 2, v & ~1u);
}

// STATION case of rtl8xxxu_add_interface (core.c:6746-6756, 6791-6793): beacon block, link type, MAC.
IOReturn RTL8188EUCore::addStationInterface()
{
    IOReturn r; uint8_t v;
    if ((r = stopTxBeacon()) != kIOReturnSuccess) return r;
    if ((r = read8(kRegBeaconCtrl, &v)) != kIOReturnSuccess) return r;
    if ((r = write8(kRegBeaconCtrl, v | kBeaconAtim | kBeaconFunctionEnable | kBeaconDisableTsfUpdate)) != kIOReturnSuccess) return r;
    if ((r = setLinkType(kMsrLinkStation)) != kIOReturnSuccess) return r;
    return setMacAddr();
}

// rtl8xxxu_set_basic_rates, 2.4 GHz (core.c:4748). rate_cfg is a bitmap in rtl rate order (bit0 = 1M ... bit11 = 54M).
IOReturn RTL8188EUCore::setBasicRates(uint32_t rateCfg)
{
    uint32_t v; IOReturn r;
    rateCfg &= kResponseRateBitmapAll;
    if ((r = read32(kRegResponseRateSet, &v)) != kIOReturnSuccess) return r;
    v = (v & kResponseRateInit2g) | rateCfg;
    if ((r = write32(kRegResponseRateSet, v)) != kIOReturnSuccess) return r;
    uint8_t idx = 0;
    if (rateCfg) idx = (uint8_t)(31 - __builtin_clz(rateCfg));   // __fls
    return write8(kRegInirtsRateSel, idx);
}

// BSS_CHANGED_ERP_PREAMBLE (core.c:4968).
IOReturn RTL8188EUCore::setShortPreamble(bool on)
{
    uint32_t v; IOReturn r = read32(kRegResponseRateSet, &v);
    if (r != kIOReturnSuccess) return r;
    return write32(kRegResponseRateSet, on ? (v | kRsrAckShortPreamble) : (v & ~kRsrAckShortPreamble));
}

// BSS_CHANGED_ERP_SLOT + rtl8xxxu_set_aifs (core.c:4979, 4801). sifs = 16 if the peer is 11n on 2.4 GHz else 10.
IOReturn RTL8188EUCore::setSlot(bool shortSlot, bool peerHt)
{
    const uint8_t slot = shortSlot ? 9 : 20, sifs = peerHt ? 16 : 10;
    IOReturn r = write8(kRegSlot, slot);
    if (r != kIOReturnSuccess) return r;
    static const uint16_t regs[4] = {kRegEdcaVo, kRegEdcaVi, kRegEdcaBe, kRegEdcaBk};
    for (int i = 0; i < 4; i++) {
        uint32_t v;
        if ((r = read32(regs[i], &v)) != kIOReturnSuccess) return r;
        uint8_t aifsn = v & 0xff;
        if (aifsn < 2 || aifsn > 15) continue;     // not set yet or already converted (same test as Linux)
        v = (v & ~0xffu) | (uint8_t)(aifsn * slot + sifs);
        if ((r = write32(regs[i], v)) != kIOReturnSuccess) return r;
    }
    return kIOReturnSuccess;
}

// BSS_CHANGED_ASSOC, "joinbss sequence" without the H2C parts (core.c:4930-4955).
IOReturn RTL8188EUCore::joinBss(uint16_t aid)
{
    IOReturn r;
    if ((r = write8(kRegBcnMaxErr, 0xff)) != kIOReturnSuccess) return r;
    if ((r = stopTxBeacon()) != kIOReturnSuccess) return r;
    if ((r = write16(kRegBcnPsrRpt, 0xc000 | aid)) != kIOReturnSuccess) return r;
    return reportConnect(0, true);                       // report_connect(priv, 0, H2C_MACID_ROLE_AP, true)
}

// BSS_CHANGED_ASSOC, disassociated branch (core.c:4957).
IOReturn RTL8188EUCore::leaveBss()
{
    uint8_t v; IOReturn r = read8(kRegBeaconCtrl, &v);
    if (r != kIOReturnSuccess) return r;
    if ((r = write8(kRegBeaconCtrl, v | kBeaconDisableTsfUpdate)) != kIOReturnSuccess) return r;
    return reportConnect(0, false);
}

// rtl8xxxu_set_key SET_KEY, CCMP only (core.c:6974-7041) + rtl8xxxu_cam_write (core.c:4454).
// Returns the CAM index used in *hwIdx. key16 is the 128-bit TK. Pairwise: mac = peer address; group: mac = BSSID.
IOReturn RTL8188EUCore::setKeyCcmp(uint8_t keyidx, bool pairwise, const uint8_t *mac, const uint8_t *key16, uint8_t *hwIdx)
{
    if (keyidx > 3) return kIOReturnUnsupported;
    IOReturn r; uint16_t cr; uint8_t i0 = 0xff;
    for (uint8_t i = 0; i < kMaxSecCam; i++) if (!(_camMap & (1u << i))) { i0 = i; break; }
    if (i0 == 0xff) return kIOReturnNoResources;

    if ((r = read16(kRegCr, &cr)) != kIOReturnSuccess) return r;
    if ((r = write16(kRegCr, cr | kCrSecurityEnable)) != kIOReturnSuccess) return r;
    const uint8_t sec = kSecCfgTxSecEnable | kSecCfgTxbcUseDefkey | kSecCfgRxSecEnable | kSecCfgRxbcUseDefkey |
                        kSecCfgTxUseDefkey | kSecCfgRxUseDefkey;
    if ((r = write8(kRegSecurityCfg, sec)) != kIOReturnSuccess) return r;

    const uint32_t addr = (uint32_t)i0 << kCamCmdKeyShift;
    uint32_t ctrl = (kCipherCcmpLow & 0x0f) << 2 | keyidx | kCamWriteValid;
    if (!pairwise) ctrl |= 1u << 6;
    for (int j = 5; j >= 0; j--) {      // same order as Linux: entry 5 down to 0, 100 us between
        uint32_t v;
        if (j == 0) v = ctrl | ((uint32_t)mac[0] << 16) | ((uint32_t)mac[1] << 24);
        else if (j == 1) v = mac[2] | (mac[3] << 8) | ((uint32_t)mac[4] << 16) | ((uint32_t)mac[5] << 24);
        else { int i = (j - 2) << 2; v = key16[i] | (key16[i+1] << 8) | ((uint32_t)key16[i+2] << 16) | ((uint32_t)key16[i+3] << 24); }
        if ((r = write32(kRegCamWrite, v)) != kIOReturnSuccess) return r;
        if ((r = write32(kRegCamCmd, kCamCmdPolling | kCamCmdWrite | (addr + j))) != kIOReturnSuccess) return r;
        IODelay(100);
    }
    _camMap |= 1u << i0;
    *hwIdx = i0;
    return kIOReturnSuccess;
}

// rtl8xxxu_set_key DISABLE_KEY (core.c:7043).
IOReturn RTL8188EUCore::clearKey(uint8_t hwIdx)
{
    if (hwIdx >= kMaxSecCam) return kIOReturnBadArgument;
    IOReturn r = write32(kRegCamWrite, 0);
    if (r != kIOReturnSuccess) return r;
    r = write32(kRegCamCmd, kCamCmdPolling | kCamCmdWrite | ((uint32_t)hwIdx << kCamCmdKeyShift));
    if (r == kIOReturnSuccess) _camMap &= ~(1u << hwIdx);
    return r;
}


// Stage 4c selftest: write the link/key registers and read them back. Uses made-up BSSID/key values (locally administered
// 02:... address, all-zero-ish key) and restores link type NONE afterwards. Only proves the registers accept writes.
void RTL8188EUCore::linkSelfTest()
{
    const uint8_t testBssid[6] = {0x02, 0x11, 0x22, 0x33, 0x44, 0x55};
    const uint8_t testKey[16] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f};
    IOReturn ra = addStationInterface(), rb = setBssid(testBssid), rc = setBasicRates(0x15), rd = setShortPreamble(true);
    IOReturn re = setSlot(true, true), rf = joinBss(1);
    uint8_t msr = 0, bss[6] = {}, mac[6] = {}, slot = 0, inirts = 0; uint32_t rsr = 0, bpsr = 0, be = 0; uint16_t cr = 0;
    read8(kRegMsr, &msr); read8(kRegSlot, &slot); read8(kRegInirtsRateSel, &inirts);
    for (int i = 0; i < 6; i++) { read8(kRegBssid + i, &bss[i]); read8(kRegMacid + i, &mac[i]); }
    read32(kRegResponseRateSet, &rsr); read32(kRegBcnPsrRpt - 0, &bpsr); read32(kRegEdcaBe, &be);
    IOLog(LOGP "link_selftest: add_if=0x%x bssid=0x%x rates=0x%x preamble=0x%x slot=0x%x join=0x%x\n", ra, rb, rc, rd, re, rf);
    IOLog(LOGP "link_selftest: MSR=0x%02x (expect 0x02) MACID=%02x:%02x:%02x:%02x:%02x:%02x (efuse) BSSID=%02x:%02x:%02x:%02x:%02x:%02x (expect 02:11:22:33:44:55) "
          "RRSR=0x%08x (expect bit23 set, low bits 0x15f|0x15) INIRTS=%u (expect 4) SLOT=%u (expect 9) BCN_PSR_RPT lo16=0x%04x (written 0xc001; bits15:14 do not read back, expect 0x0001) EDCA_BE=0x%08x\n",
          msr, mac[0], mac[1], mac[2], mac[3], mac[4], mac[5], bss[0], bss[1], bss[2], bss[3], bss[4], bss[5], rsr, inirts, slot, bpsr & 0xffff, be);
    uint8_t hw = 0xff, hw2 = 0xff; uint32_t camCmd = 0xffffffff, camCmd2 = 0xffffffff;
    IOReturn rk = setKeyCcmp(0, true, testBssid, testKey, &hw);
    read32(kRegCamCmd, &camCmd); read16(kRegCr, &cr);
    uint8_t sec = 0; read8(kRegSecurityCfg, &sec);
    IOReturn rk2 = setKeyCcmp(1, false, testBssid, testKey, &hw2);
    IOReturn rc1 = clearKey(hw), rc2 = clearKey(hw2);
    read32(kRegCamCmd, &camCmd2);
    IOLog(LOGP "link_selftest: set_key=0x%x (cam %u) set_key2=0x%x (cam %u) clear=0x%x/0x%x CAM_CMD after write=0x%08x after clear=0x%08x (bit31 should be 0) "
          "CR=0x%04x (bit9 security) SECCFG=0x%02x (expect 0xcf)\n", rk, hw, rk2, hw2, rc1, rc2, camCmd, camCmd2, cr, sec);
    uint8_t hmtfr = 0xff; read8(kRegHmtfr, &hmtfr);
    IOReturn rl = leaveBss();
    IOLog(LOGP "link_selftest: join(+H2C media status)=0x%x leave(+H2C)=0x%x next_mbox=%u HMTFR=0x%02x (mailbox busy bits should clear)\n", rf, rl, _nextMbox, hmtfr);
    setLinkType(kMsrLinkNone);
}


// rtl8xxxu_gen2_h2c_cmd for commands <= 4 bytes (core.c:1000): wait for the mailbox, write the 32-bit word, rotate mailbox.
// Linux's wait loop (`while (retry--)` then `if (!retry)`) cannot detect a timeout; this one does.
IOReturn RTL8188EUCore::h2cCmd4(uint32_t data)
{
    const uint8_t mbox = _nextMbox;
    uint8_t v = 0; bool ready = false;
    for (int retry = 0; retry < 100; retry++) {
        IOReturn r = read8(kRegHmtfr, &v);
        if (r != kIOReturnSuccess) return r;
        if (!(v & (1u << mbox))) { ready = true; break; }
    }
    if (!ready) return kIOReturnBusy;
    IOReturn r = write32(kRegHmbox0 + mbox * 4, data);
    if (r != kIOReturnSuccess) return r;
    _nextMbox = (mbox + 1) % kH2cMaxMbox;
    return kIOReturnSuccess;
}

// rtl8xxxu_gen2_report_connect (core.c:4630): H2C media status report. "The firmware turns on the rate control when it
// knows it's connected" per the Linux comment, although 8188eu rate selection is done by the driver (ra_info), see docs.
// Linux passes macid 0, role AP (we are the station, the peer is the AP).
IOReturn RTL8188EUCore::reportConnect(uint8_t macid, bool connect)
{
    const uint8_t parm = (connect ? 1 : 0) | ((kH2cRoleAp << 4) & 0xf0);
    return h2cCmd4(kH2cMediaStatusRpt | ((uint32_t)parm << 8) | ((uint32_t)macid << 16));   // macid_end byte = 0
}

// Stage 4a: passive RX scan. Synchronous bulk IN, 20 MHz channels 1-13, no aggregation (init_aggregation cleared it).
// rtl8xxxu_rxdesc16 (rtl8xxxu.h:135) is 6 dwords = 24 bytes; bit positions below are derived from that LE bitfield layout:
//   dw0: pktlen[13:0] crc32[14] icverr[15] drvinfo_sz[19:16] shift[25:24] phy_stats[26]
//   dw2: pkt_cnt[23:16]   dw3: rpt_sel[15:14]
// Frame starts at 24 + drvinfo_sz*8 + shift (parse_rxdesc16, core.c:6320). Aggregated URBs (pkt_cnt > 1) are not walked.
IOReturn RTL8188EUCore::rxScan()
{
    enum { kRxBufLen = 4096, kDwellMs = 350, kMaxAps = 32 };
    if (!_bulkIn) return kIOReturnNotReady;
    IOBufferMemoryDescriptor *buf = IOBufferMemoryDescriptor::inTaskWithOptions(kernel_task, kIODirectionIn, kRxBufLen, 4);
    if (!buf) return kIOReturnNoMemory;
    uint8_t *b = (uint8_t *)buf->getBytesNoCopy();
    struct Ap { uint8_t bssid[6]; char ssid[33]; uint8_t ds; uint8_t seenCh; } aps[kMaxAps];
    uint32_t nAps = 0, totalFrames = 0, totalProbeResp = 0;

    // Stage 4b: active scan. MAC from efuse into REG_MACID so unicast probe responses pass RCR_ACCEPT_PHYS_MATCH.
    IOReturn mr = setMacAddr();
    IOBufferMemoryDescriptor *txBuf = IOBufferMemoryDescriptor::inTaskWithOptions(kernel_task, kIODirectionOut, 256, 4);
    const bool active = (mr == kIOReturnSuccess) && txBuf;
    IOLog(LOGP "rx_scan: set_mac %s (0x%08x), active probe requests %s\n", mr == kIOReturnSuccess ? "OK" : "FAILED", mr, active ? "on" : "off");
    uint16_t txSeq = 0;

    for (int ch = 1; ch <= 13; ch++) {
        IOReturn r = setChannel(ch);
        if (r != kIOReturnSuccess) { IOLog(LOGP "rx_scan: setChannel(%d) failed 0x%08x\n", ch, r); continue; }
        // Drop frames still queued from the previous channel (v0.10.0 showed a ch11 beacon attributed to ch1).
        for (int d = 0; d < 16; d++) { uint32_t g = 0; if (_bulkIn->io(buf, kRxBufLen, g, 20) != kIOReturnSuccess) break; }
        uint32_t frames = 0, beacons = 0, crcBad = 0, c2h = 0, ioErr = 0, timeouts = 0, probeResp = 0, txOk = 0, txFail = 0;
        IOReturn lastTx = kIOReturnSuccess;
        if (active) {
            // Probe request, broadcast DA/BSSID, wildcard SSID, 1/2/5.5/11 + 6/9/12/18 (ext: 24/36/48/54), DS channel.
            uint8_t pr[64]; uint16_t n = 0;
            pr[n++] = 0x40; pr[n++] = 0x00; pr[n++] = 0; pr[n++] = 0;
            for (int i = 0; i < 6; i++) pr[n++] = 0xff;
            for (int i = 0; i < 6; i++) pr[n++] = _efuse[kEfuseOffMac + i];
            for (int i = 0; i < 6; i++) pr[n++] = 0xff;
            txSeq++; pr[n++] = (uint8_t)((txSeq << 4) & 0xff); pr[n++] = (uint8_t)((txSeq << 4) >> 8);
            pr[n++] = 0; pr[n++] = 0;                                                       // SSID, wildcard
            const uint8_t rates[] = {0x82, 0x84, 0x8b, 0x96, 0x0c, 0x12, 0x18, 0x24};
            pr[n++] = 1; pr[n++] = sizeof(rates); memcpy(pr + n, rates, sizeof(rates)); n += sizeof(rates);
            const uint8_t ext[] = {0x30, 0x48, 0x60, 0x6c};
            pr[n++] = 50; pr[n++] = sizeof(ext); memcpy(pr + n, ext, sizeof(ext)); n += sizeof(ext);
            pr[n++] = 3; pr[n++] = 1; pr[n++] = (uint8_t)ch;
            lastTx = txMgmt(txBuf, pr, n, txSeq);
            if (lastTx == kIOReturnSuccess) txOk++; else txFail++;
        }
        uint64_t startAbs, nowAbs, ns = 0;
        clock_get_uptime(&startAbs);
        while (ns < (uint64_t)kDwellMs * 1000000ull) {
            uint32_t got = 0;
            IOReturn ir = _bulkIn->io(buf, kRxBufLen, got, 100);
            clock_get_uptime(&nowAbs);
            absolutetime_to_nanoseconds(nowAbs - startAbs, &ns);
            if (ir == kIOReturnTimeout) { timeouts++; continue; }
            if (ir != kIOReturnSuccess) { ioErr++; if (ioErr > 3) break; continue; }
            if (got < 24) continue;
            const uint32_t dw0 = OSReadLittleInt32(b, 0), dw3 = OSReadLittleInt32(b, 12);
            uint32_t pktLen = dw0 & 0x3fff, drv = ((dw0 >> 16) & 0xf) * 8, shift = (dw0 >> 24) & 3;
            if (((dw3 >> 14) & 3) != 0) { c2h++; continue; }          // rpt_sel != 0: C2H report, not a frame
            frames++;
            if (dw0 & (1u << 14)) { crcBad++; continue; }              // crc32 error
            uint32_t off = 24 + drv + shift;
            if (pktLen < 36 || off + pktLen > got) continue;
            const uint8_t *f = b + off;
            if ((f[0] & 0xfc) != 0x80 && (f[0] & 0xfc) != 0x50) continue;   // beacon / probe response only
            if ((f[0] & 0xfc) == 0x50) probeResp++;
            beacons++;
            const uint8_t *bssid = f + 16;
            char ssid[33] = {0}; uint8_t ds = 0;
            for (uint32_t i = 36; i + 2 <= pktLen; ) {
                uint8_t tag = f[i], len = f[i + 1];
                if (i + 2 + len > pktLen) break;
                if (tag == 0) { uint8_t n = len > 32 ? 32 : len; for (uint8_t k = 0; k < n; k++) ssid[k] = (f[i+2+k] >= 32 && f[i+2+k] < 127) ? f[i+2+k] : '?'; }
                else if (tag == 3 && len == 1) ds = f[i + 2];
                i += 2 + len;
            }
            bool known = false;
            for (uint32_t k = 0; k < nAps; k++) if (!memcmp(aps[k].bssid, bssid, 6)) { known = true; break; }
            if (!known && nAps < kMaxAps) {
                memcpy(aps[nAps].bssid, bssid, 6); memcpy(aps[nAps].ssid, ssid, 33); aps[nAps].ds = ds; aps[nAps].seenCh = (uint8_t)ch;
                nAps++;
                IOLog(LOGP "rx_scan AP: ssid=\"%s\" bssid=%02x:%02x:%02x:%02x:%02x:%02x ds_ch=%u heard_on=%d\n",
                      ssid, bssid[0], bssid[1], bssid[2], bssid[3], bssid[4], bssid[5], ds, ch);
            }
        }
        totalFrames += frames; totalProbeResp += probeResp;
        IOLog(LOGP "rx_scan ch%d: frames=%u mgmt(beacon/probe)=%u probe_resp=%u crc_bad=%u c2h=%u timeouts=%u io_err=%u tx_ok=%u tx_fail=%u (0x%08x)\n",
              ch, frames, beacons, probeResp, crcBad, c2h, timeouts, ioErr, txOk, txFail, lastTx);
    }
    if (txBuf) txBuf->release();
    buf->release();
    IOLog(LOGP "rx_scan done: %u frames total, %u probe responses, %u unique AP(s)\n", totalFrames, totalProbeResp, nAps);
    return kIOReturnSuccess;
}

IOReturn RTL8188EUCore::phyLcCalibrate()
{
    IOReturn r; uint32_t lstf, rfAmode = 0, v32;
    if ((r = read32(kRegOfdm1Lstf, &lstf)) != kIOReturnSuccess) return r;
    bool contTx = (lstf & kOfdmLstfMask) != 0;
    if (contTx) {
        if ((r = write32(kRegOfdm1Lstf, lstf & ~(uint32_t)kOfdmLstfMask)) != kIOReturnSuccess) return r;
        if ((r = rfRead(kRf6052RegAc, &rfAmode)) != kIOReturnSuccess) return r;
        if ((r = rfWrite(kRf6052RegAc, (rfAmode & 0x8ffff) | 0x10000)) != kIOReturnSuccess) return r;
    } else {
        if ((r = write8(kRegTxpause, 0xff)) != kIOReturnSuccess) return r;
    }
    if ((r = rfRead(kRf6052RegModeAg, &v32)) != kIOReturnSuccess) return r;
    if ((r = rfWrite(kRf6052RegModeAg, v32 | 0x08000)) != kIOReturnSuccess) return r;
    IOSleep(100);
    if (contTx) {
        if ((r = write32(kRegOfdm1Lstf, lstf)) != kIOReturnSuccess) return r;
        return rfWrite(kRf6052RegAc, rfAmode);
    }
    return write8(kRegTxpause, 0x00);
}

// Remaining part of rtl8xxxu_init_device (core.c:4283-4440) for the 8188EU, up to (not including) IQ calibration,
// which is deferred (8188e.c:906, ~350 lines, not needed for scan to start), as are set_crystal_cap/CFO tracking and
// the software rate-control init.
IOReturn RTL8188EUCore::initTail()
{
    IOReturn r; uint8_t v8; uint32_t v32;
#define TRY(x) do { if ((r = (x)) != kIOReturnSuccess) { IOLog(LOGP "initTail: %s failed 0x%08x (line %d)\n", #x, r, __LINE__); return r; } } while (0)
    TRY(setTxPower(1, false));                               // default power, channel 1, 20 MHz
    TRY(read8(kRegLedcfg2, &v8));                            // let the 8051 take antenna control
    TRY(write8(kRegLedcfg2, v8 | kLedcfg2DpdtSelect));
    TRY(write8(kRegHwseqCtrl, 0xff));
    TRY(write32(kRegBarModeCtrl, 0x0201ffff));
    TRY(read8(kRegGpioMuxcfg, &v8));                         // 8188E/F/8192F GPIO init
    TRY(write8(kRegGpioMuxcfg, v8 & ~kGpioMuxcfgIoSelEnbt));
    TRY(phyLcCalibrate());
    // gen2_thermal_meter, chip != 8188F/8710B
    TRY(rfWrite(kRf6052RegTMeter8723b, 0x37cf8));
    TRY(write8(kRegNavUpper, (30000 + kNavUpperUnit - 1) / kNavUpperUnit));
    TRY(write8(kRegUsbHrpwm, 0x00));                         // RTL8192E/RTL8188E
    TRY(read32(kRegFwhwTxqCtrl, &v32));
    TRY(write32(kRegFwhwTxqCtrl, v32 | kFwhwTxqCtrlXmitMgmtAck));
#undef TRY
    return kIOReturnSuccess;
}

// Claim the USB interface (owner = the IOService that matched it), enumerate bulk endpoints, allocate control buffers.
bool RTL8188EUCore::attach(IOService *owner, IOUSBHostInterface *iface)
{
    _owner = owner;
    _iface = iface;
    if (!_iface) { IOLog(LOGP "provider is not IOUSBHostInterface\n"); return false; }

    if (!_iface->open(_owner)) { IOLog(LOGP "open interface failed\n"); _iface = nullptr; return false; }
    _open = true;
    _iface->retain();

    const StandardUSB::InterfaceDescriptor *id = _iface->getInterfaceDescriptor();
    IOLog(LOGP "attached: interface %u class 0x%02x endpoints %u\n",
          id->bInterfaceNumber, id->bInterfaceClass, id->bNumEndpoints);

    // Enumerate endpoints (log only; pipes kept for Stage 2 TX/RX work).
    const StandardUSB::EndpointDescriptor *ep = nullptr;
    while ((ep = (const StandardUSB::EndpointDescriptor *)
            StandardUSB::getNextAssociatedDescriptorWithType(
                _iface->getConfigurationDescriptor(), id,
                (const StandardUSB::Descriptor *)ep, kDescriptorTypeEndpoint)) != nullptr) {
        uint8_t addr = StandardUSB::getEndpointAddress(ep);
        uint8_t dir  = StandardUSB::getEndpointDirection(ep);
        uint8_t type = StandardUSB::getEndpointType(ep);
        IOLog(LOGP "endpoint 0x%02x dir=%s type=%u\n", addr,
              dir == kIOUSBEndpointDirectionIn ? "IN" : "OUT", type);
        if (type != kIOUSBEndpointTypeBulk) continue;
        if (dir == kIOUSBEndpointDirectionIn && !_bulkIn) {
            _bulkIn = _iface->copyPipe(addr);
        } else if (dir == kIOUSBEndpointDirectionOut && _nBulkOut < 4) {
            _bulkOut[_nBulkOut] = _iface->copyPipe(addr);
            if (_bulkOut[_nBulkOut]) _nBulkOut++;
        }
    }
    IOLog(LOGP "bulk IN %s, bulk OUT count %u\n", _bulkIn ? "ok" : "MISSING", _nBulkOut);

    _ctlBuf = IOBufferMemoryDescriptor::inTaskWithOptions(
        kernel_task, kIODirectionInOut, 4, 4);
    _blkBuf = IOBufferMemoryDescriptor::inTaskWithOptions(
        kernel_task, kIODirectionInOut, kWriteNBlock, 4);
    if (!_ctlBuf || !_blkBuf) { closeAll(); return false; }
    return true;
}

// Chip identification, efuse, power-on, firmware, MAC/BB/RF init, then the hardware self-tests. Always returns true;
// failures are logged (the probe kext stays loaded so the log can be read).
bool RTL8188EUCore::bringUp()
{
    // Step 2 of the test protocol: read-only chip identification.
    uint32_t sysCfg = 0;
    IOReturn r = regRead(kRegSysCfg, &sysCfg, sizeof(sysCfg));
    if (r != kIOReturnSuccess) {
        IOLog(LOGP "SYS_CFG read failed: 0x%08x\n", r);
    } else {
        uint32_t cut = (sysCfg & kSysCfgChipVerMask) >> 12;
        IOLog(LOGP "REG_SYS_CFG(0x00f0) = 0x%08x cut=%u%s%s\n", sysCfg, cut,
              (sysCfg & kSysCfgTrpVauxEn) ? " TEST-CHIP(unsupported by rtl8xxxu)" : "",
              cut == 8 ? " CUT-I(unsupported by rtl8xxxu)" : "");
        // Test protocol step 2b: MAC from efuse. Skip on chips rtl8xxxu rejects.
        if (!(sysCfg & kSysCfgTrpVauxEn) && cut != 8) {
            IOReturn er = efuseReadAll();
            if (er != kIOReturnSuccess) IOLog(LOGP "efuse read failed: 0x%08x\n", er);
            else {
                logEfuse();
                // Stage 3b-1: MAC power-on only (no firmware yet).
                IOReturn pr = powerOn();
                uint16_t cr = 0, clkr = 0; uint32_t fsmco = 0;
                read16(kRegCr, &cr); read16(kRegSysClkr, &clkr); read32(kRegApsFsmco, &fsmco);
                IOLog(LOGP "power_on %s (0x%08x): CR=0x%04x SYS_CLKR=0x%04x (MAC_CLK %s) APS_FSMCO=0x%08x\n",
                      pr == kIOReturnSuccess ? "OK" : "FAILED", pr, cr, clkr,
                      (clkr & kSysClkMacClkEnable) ? "on" : "OFF", fsmco);
                if (pr == kIOReturnSuccess) {
                    IOReturn fr = loadFirmware();
                    uint32_t fwdl = 0; read32(kRegMcuFwDl, &fwdl);
                    IOLog(LOGP "firmware %s (0x%08x): FW_DL=0x%08x\n",
                          fr == kIOReturnSuccess ? "RUNNING" : "FAILED", fr, fwdl);
                    if (fr == kIOReturnSuccess) {
                        // Stage 3c-1: MAC register table (Linux order: after firmware start).
                        IOReturn mr = initMac();
                        uint16_t aggr = 0; uint8_t b0 = 0, b1 = 0;
                        read16(kRegMaxAggrNum, &aggr); read8(0x428, &b0); read8(0x652, &b1);
                        IOLog(LOGP "init_mac %s (0x%08x): MAX_AGGR_NUM=0x%04x (expect 0x0707) 0x428=0x%02x (expect 0x0a) 0x652=0x%02x (expect 0x20)\n",
                              mr == kIOReturnSuccess ? "OK" : "FAILED", mr, aggr, b0, b1);
                        if (mr == kIOReturnSuccess) {
                            // Stage 3c-2: BB init + RF accessor check (Linux order: init_mac -> init_phy_bb).
                            IOReturn br = initPhyBb();
                            uint32_t bb800 = 0, bb804 = 0, bb808 = 0, rf00 = 0xdeadbeef;
                            read32(0x800, &bb800); read32(0x804, &bb804); read32(0x808, &bb808);
                            IOReturn rr = rfRead(0x00, &rf00);
                            IOLog(LOGP "init_phy_bb %s (0x%08x): 0x800=0x%08x 0x804=0x%08x 0x808=0x%08x; rf_read(A,0x00) %s 0x%05x (informational, RF not initialised yet)\n",
                                  br == kIOReturnSuccess ? "OK" : "FAILED", br, bb800, bb804, bb808,
                                  rr == kIOReturnSuccess ? "=" : "FAILED", rf00);
                            if (br == kIOReturnSuccess) {
                                // Stage 3c-3: radio A table (Linux order: init_phy_bb -> init_phy_rf).
                                IOReturn fr2 = initPhyRf();
                                uint32_t chk = 0, bad = 0, badReg = 0, badGot = 0;
                                IOReturn vr = (fr2 == kIOReturnSuccess) ? rfVerify(&chk, &bad, &badReg, &badGot) : fr2;
                                IOLog(LOGP "init_phy_rf %s (0x%08x): verify %s: %u regs read back, %u mismatch (first: reg 0x%02x got 0x%05x)\n",
                                      fr2 == kIOReturnSuccess ? "OK" : "FAILED", fr2,
                                      vr == kIOReturnSuccess ? "ok" : "ERROR", chk, bad, badReg, badGot);
                                if (fr2 == kIOReturnSuccess) {
                                    // Stage 3c-4: WMAC/LLT/EDCA/beacon block (Linux order: init_phy_rf -> RFSW ... CAM).
                                    IOReturn wr = initWmac();
                                    uint32_t rcr = 0, llt = 0, cam = 0, sw = 0, edca = 0;
                                    uint16_t cr2 = 0, mx = 0; uint8_t drv = 0, bnd = 0;
                                    read32(kRegRcr, &rcr); read32(kRegLltInit, &llt); read32(kRegCamCmd, &cam);
                                    read32(kRegFpgaXaRfSwCtrl, &sw); read32(kRegEdcaBe, &edca);
                                    read16(kRegCr, &cr2); read8(kRegRxDrvinfoSz, &drv); read8(kRegTrxffBndy, &bnd);
                                    read16(kRegSifsCck, &mx);
                                    IOLog(LOGP "init_wmac %s (0x%08x): CR=0x%04x RCR=0x%08x (expect 0x7000600e) RX_DRVINFO=%u (expect 4) "
                                          "TRXFF_BNDY=0x%02x (expect 0xaa) RFSW=0x%08x (expect 0x07000760) SIFS_CCK=0x%04x (expect 0x100a) "
                                          "EDCA_BE=0x%08x (expect 0x005ea42b) LLT_INIT=0x%08x CAM_CMD=0x%08x\n",
                                          wr == kIOReturnSuccess ? "OK" : "FAILED", wr, cr2, rcr, drv, bnd, sw, mx, edca, llt, cam);
                                    if (wr == kIOReturnSuccess) {
                                        // Stage 3c-5: tx power, LC calibration, thermal meter, NAV etc.
                                        IOReturn tr = initTail();
                                        uint32_t agc = 0, ofdmr = 0, rf18 = 0, rf42 = 0; uint8_t nav = 0, hw = 0;
                                        read32(kRegTxAgcACck1Mcs32, &agc); read32(kRegTxAgcARate1806, &ofdmr);
                                        rfRead(kRf6052RegModeAg, &rf18); rfRead(kRf6052RegTMeter8723b, &rf42);
                                        read8(kRegNavUpper, &nav); read8(kRegHwseqCtrl, &hw);
                                        IOLog(LOGP "init_tail %s (0x%08x): 0xe08=0x%08x 0xe00=0x%08x RF18=0x%05x (LC cal bit15 should be clear) "
                                              "RF42=0x%05x NAV_UPPER=0x%02x (expect 0xeb) HWSEQ=0x%02x (expect 0xff)\n",
                                              tr == kIOReturnSuccess ? "OK" : "FAILED", tr, agc, ofdmr, rf18, rf42, nav, hw);
                                        if (tr == kIOReturnSuccess) {
                                            // Stage 3d: channel switch 6 then 11, read RF18 back (low 12 bits only; bit 15 self-clears).
                                            uint32_t a = 0, b = 0;
                                            IOReturn c1 = setChannel(6); rfRead(kRf6052RegModeAg, &a);
                                            IOReturn c2 = setChannel(11); rfRead(kRf6052RegModeAg, &b);
                                            IOLog(LOGP "set_channel %s (0x%08x/0x%08x): RF18[11:0] ch6=0x%03x (expect 0xc06) ch11=0x%03x (expect 0xc0b)\n",
                                                  (c1 == kIOReturnSuccess && c2 == kIOReturnSuccess) ? "OK" : "FAILED", c1, c2, a & 0xfff, b & 0xfff);
                                            if (c1 == kIOReturnSuccess && c2 == kIOReturnSuccess) {
                                                uint32_t rc = 0, cr3 = 0;
                                                read32(kRegRcr, &rc); read32(kRegCr, &cr3);
                                                IOLog(LOGP "rx_scan start: RCR=0x%08x CR=0x%08x\n", rc, cr3);
                                                IOReturn xr = rxScan();
                                                IOLog(LOGP "rx_scan returned 0x%08x\n", xr);
                                                linkSelfTest();
                                                asyncSelfTest();
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    return true;
}

void RTL8188EUCore::getMac(uint8_t mac[6]) { memcpy(mac, _efuse + kEfuseOffMac, 6); }
unsigned RTL8188EUCore::txFreeSlots() { return kTxSlots - (unsigned)__builtin_popcount((unsigned)_txBusyMask); }

// Same chain as bringUp() (same calls, same order, hardware-proven) without register dumps or self-tests.
// Linux order: identify -> efuse -> power_on -> firmware -> init_mac -> init_phy_bb -> init_phy_rf -> init_wmac -> tail.
IOReturn RTL8188EUCore::initHardware()
{
    uint32_t sysCfg = 0;
    IOReturn r = regRead(kRegSysCfg, &sysCfg, sizeof(sysCfg));
    if (r != kIOReturnSuccess) return r;
    if ((sysCfg & kSysCfgTrpVauxEn) || ((sysCfg & kSysCfgChipVerMask) >> 12) == 8) return kIOReturnUnsupported;
#define STEP(call, name) do { r = (call); if (r != kIOReturnSuccess) { IOLog(LOGP "initHardware: " name " FAILED 0x%08x\n", r); return r; } } while (0)
    STEP(efuseReadAll(), "efuse");
    STEP(powerOn(), "power_on");
    STEP(loadFirmware(), "firmware");
    STEP(initMac(), "init_mac");
    STEP(initPhyBb(), "init_phy_bb");
    STEP(initPhyRf(), "init_phy_rf");
    STEP(initWmac(), "init_wmac");
    STEP(initTail(), "init_tail");
#undef STEP
    IOLog(LOGP "initHardware OK, MAC %02x:%02x:%02x:%02x:%02x:%02x\n", _efuse[kEfuseOffMac], _efuse[kEfuseOffMac + 1],
          _efuse[kEfuseOffMac + 2], _efuse[kEfuseOffMac + 3], _efuse[kEfuseOffMac + 4], _efuse[kEfuseOffMac + 5]);
    return kIOReturnSuccess;
}

// Stop async I/O, release pipes/buffers and close the interface. Safe to call repeatedly (hot-unplug, stop, free).
void RTL8188EUCore::closeAll()
{
    asyncStop();
    if (_bulkIn) { _bulkIn->abort(); _bulkIn->release(); _bulkIn = nullptr; }
    for (uint32_t i = 0; i < _nBulkOut; i++) {
        if (_bulkOut[i]) { _bulkOut[i]->abort(); _bulkOut[i]->release(); _bulkOut[i] = nullptr; }
    }
    _nBulkOut = 0;
    if (_ctlBuf) { _ctlBuf->release(); _ctlBuf = nullptr; }
    if (_blkBuf) { _blkBuf->release(); _blkBuf = nullptr; }
    if (_iface) {
        if (_open) { _iface->close(_owner); _open = false; }
        _iface->release();
        _iface = nullptr;
    }
    _owner = nullptr;
}

void RTL8188EUCore::free()
{
    closeAll();
    super::free();
}
