#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# Fetch rtlwifi/rtl8188eufw.bin from linux-firmware and generate build/fw/rtl8188eu_fw.h.
# The blob is Realtek-licensed (LICENSES/LICENCE.rtlwifi_firmware.txt: binary redistribution
# without modification, with notice, no reverse engineering). It is NOT committed; the header is
# generated locally for your own build only and must not be redistributed inside a release.
set -eu
OUT="$(cd "$(dirname "$0")/.." && pwd)/build/fw"
BASE=https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain
mkdir -p "$OUT"
curl -fsSL -o "$OUT/rtl8188eufw.bin" "$BASE/rtlwifi/rtl8188eufw.bin"
curl -fsSL -o "$OUT/LICENCE.rtlwifi_firmware.txt" "$BASE/LICENSES/LICENCE.rtlwifi_firmware.txt"
SIZE=$(wc -c < "$OUT/rtl8188eufw.bin" | tr -d ' ')
# 15262 bytes at linux-firmware main on 2026-10-07; warn (not fail) if upstream changed it.
[ "$SIZE" = 15262 ] || echo "note: firmware size is $SIZE (was 15262); check WHENCE version" >&2
{
  echo "/* generated by scripts/fetch-rtl8188eu-fw.sh - Realtek firmware, do not commit or redistribute */"
  echo "static const unsigned char rtl8188eu_fw[] = {"
  xxd -i < "$OUT/rtl8188eufw.bin"
  echo "};"
  echo "static const unsigned int rtl8188eu_fw_len = $SIZE;"
} > "$OUT/rtl8188eu_fw.h"
echo "OK $OUT/rtl8188eu_fw.h ($SIZE bytes)"
