#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# Extract register init tables from Linux rtl8xxxu 8188e.c (GPL-2.0-only, torvalds/linux master)
# into build/fw/rtl8188eu_tables.h. Mechanical copy, no retyping. Usage: gen-rtl8188eu-tables.py [8188e.c]
import re, sys, os, urllib.request
URL = "https://raw.githubusercontent.com/torvalds/linux/master/drivers/net/wireless/realtek/rtl8xxxu/8188e.c"
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "build", "fw", "rtl8188eu_tables.h")
src = open(sys.argv[1]).read() if len(sys.argv) > 1 else urllib.request.urlopen(URL).read().decode()
def table(name):
    m = re.search(r"static const struct \w+ %s\[\] = \{(.*?)\n\};" % name, src, re.S)
    if not m: sys.exit("table not found: " + name)
    return re.findall(r"\{\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*\}", m.group(1))
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w") as f:
    f.write("/* generated by scripts/gen-rtl8188eu-tables.py from Linux rtl8xxxu 8188e.c (GPL-2.0-only) - do not edit */\n")
    f.write("struct Reg8Val { unsigned short reg; unsigned char val; };\n")
    t = table("rtl8188e_mac_init_table")
    assert t[-1] == ("0xffff", "0xff"), "missing terminator"
    f.write("static const Reg8Val rtl8188e_mac_init_table[] = {\n")
    for r, v in t: f.write("    {%s, %s},\n" % (r, v))
    f.write("};\n")
print("OK", out, len(t), "mac entries")
